### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by hughes** [jisaacks/GitGutter#236] opened 2015-06-28 19:50 UTC
The [release notes](https://github.com/jisaacks/GitGutter/blob/652f321a09db939bfa46af00ff9bd3eacd64d326/release_messages/dest/1.2.1.txt) popup that came as a result of a gitgutter update today was very spammy and contained no actual update information. Please don't force this stuff onto my screen again.

**Comment by jisaacks** [comment] 2015-06-30 04:23
> contained no actual update information

The only way that should have happened is if you upgraded directly to 1.2.1 from 1.2.0 which is highly unlikely since they were released about 60 seconds apart from each other.

> Please don't force this stuff onto my screen again.

I am not forcing anything onto your screen. gitgutter is a free program and you are free to not use it if you please. I put up the message to let people know the book exists, and to help a friend who put a lot of effort into making that book. 

I am not planning on pushing out new releases everyday, this was only the 3rd this year. I really didn't think anyone would be so bothered by it, and so far you are the only one who has complained. I am sorry if you think I was being spammy. If you never want to see the message again, I believe (not 100% positive) that if you install [gitgutter-edge](https://packagecontrol.io/packages/GitGutter-Edge) you won't see the release messages because it just points to `master`.

**Comment by billinghamj** [comment] 2015-06-30 12:23
+1

**Comment by Lochlan** [comment] 2015-07-02 01:24
+1, very spammy—I hope that will be the last time I see something like that.

**Comment by TimZaman** [comment] 2016-07-22 13:12
> I believe (not 100% positive) that if you install gitgutter-edge you won't see the release messages because it just points to master.

False. I like GitGutter a lot, but if you need money, add a single link and button and we'll donate 👍 . Indeed, this package information (which it is not) looks like a proper spam email to me.

**Comment by billinghamj** [comment] 2016-08-15 20:37
Just happened again today. 🙄

**Comment by TimZaman** [comment] 2016-08-15 20:55
Very spammy indeed. Those icons.. Pff

**Comment by gr4y** [comment] 2016-08-17 13:24
I just got this when I opened Sublime Text up: https://www.dropbox.com/s/u5eqg0dezh93qiy/Screenshot%202016-08-17%2015.05.56.png?dl=0

I know anyone will earn money with their work, but isn't that the wrong way to do so? Have you thought about using patreon, to make us pay you and adding an URL to the release notes? Maybe when you add a link to the GitHub Repo someone will take a look at your project and will help you? I mean it's open source, right? Why not openly asking us to donate?

**Comment by rchl** [comment] 2016-11-15 21:51
Personally I think author can do whatever he wants really, but if he will piss off users, he will probably make them move away from the plugin, or fork it, and in the end loose on both fronts.

I'll close it as it's not a bug. There is still #237 open with some related discussion.

(Disclaimer: I'm not affiliated with the author :))

**Closed by rchl** 2016-11-15 21:51 UTC
