### ISSUE TITLE
Unable to Install in Sublime Text 3 Build 3143

### ISSUE THREAD

**Issue by vishnuys** [jisaacks/GitGutter#486] opened 2018-02-27 06:16 UTC
## Description

Getting the following error while trying to Install:

```
ignored packages updated to: ["GitGutter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: Error downloading package. HTTP error 502 downloading https://bitbucket.org/teddy_beer_maniac/sublime-text-dependency-markupsafe/get/0.23.0.zip.
error: Package Control

Unable to download markupsafe. Please view the console for more details.
Package Control: The dependency 'markupsafe' could not be installed or updated
ignored packages updated to: ["Vintage"]
```

Seems like the Markupsafe link is down. Are there any alternatives or other links to it?

**Comment by deathaxe** [comment] 2018-03-03 19:56
Duplicate of https://github.com/jisaacks/GitGutter/issues/484 and invalid as it is a _Package Control_ issue.

**Closed by deathaxe** 2018-03-03 19:56 UTC
Labels: duplicate, invalid
