### ISSUE TITLE
Random files marked as modified

### ISSUE THREAD

**Issue by atomtigerzoo** [jisaacks/GitGutter#381] opened 2017-03-06 14:04 UTC
I used GitGutter without any problems until today's automatic update to the latest version.

Now Git Gutter marks all lines in random files as modified (yellow) and I cannot reproduce why. I tried removing the package, updated git on my system - still marking whole files as modified. I have the problem in multiple projects. When I use git on the command line nothing is modified, branch is clean, still Git Gutter shows modifications.

I am using ST3 with the latest GitGutter installed with Package Control.

**Comment by sbalgas** [comment] 2017-03-06 14:39
Hi, I have the same problem now.
I tried changing the Line Endings, Unix, Windows and Mac.
I am using ST3 3126.

**Comment by paranat** [comment] 2017-03-06 14:47
Having a similar problem with 1.5.0 where all lines of files are marked with red.

Running on Linux ST3 3126.

**Comment by deathaxe** [comment] 2017-03-06 16:42
This issue may most likely be caused by different `line endings` of the working file and its copy in the git repository. GitGutter uses `git archive` command to read the file from repository, which should do correct translations but this seems not to work in your case. 

To check whether this is the reason, please try the following:

1. Open command pallet
2. Type: _Preferences: GitGutter Settings
3. Add the following entry to the _GitGutter.sublime-settings_
   
   `"ignore_whitespace": "eol",`

This will call git diff with `--ignore-space-at-eol` switch.

**Comment by paranat** [comment] 2017-03-06 17:55
Yep, this seems to be the case for me. Using that setting gets rid of the incorrect change markings.

**Comment by deathaxe** [comment] 2017-03-06 18:35
I am not quite sure if `--ignore-space-at-eol` ignores `\r\n <-> \n` differences only. I guess it also ignores tabs and spaces.

That's why I created a PR which might solve the issue even with `"ignore_whitespace": "none",`.

**Comment by sbalgas** [comment] 2017-03-06 19:08
Hi, I put "ignore_whitespace": "eol", in my GitGutter Settings and I have the same problem.
But, when I change the EOL in the SublimeText, my smartgit and git status shows me this change.

Regards

**Comment by alecive** [comment] 2017-03-06 19:12
@deathaxe `ignore_whitespace` fixed the issue to me, but why this issue appeared only now in the first place? Also, I am not quite sure if there is a difference in end-of-lines in my repositories at all (at least, not that I'm aware of).

**Comment by deathaxe** [comment] 2017-03-06 19:43
GitGutter creates 2 temp files one for the content of the view and one for the file from index. They are passed to a `git diff --no-index` to get the changes.

I guess the issue is caused by the way the temporary files are created.

The view content is read via Sublime API as python string, encoded with the view's `encoding` (utf-8 by default) and written to disk. The lines of the string we get from ST are always terminated with `\n`. No matter what line-ending is set by the user in the front end. This makes sense as I normally don't want to struggle with that. As a result the temporary file contains `\n` while the file read from git may contain `\r\n` as you can see from @sbalgas`s screenshots.

I was not aware of that when I worked on the fix for issue #74.

**Comment by deathaxe** [comment] 2017-03-06 20:41
> I put "ignore_whitespace": "eol", in my GitGutter Settings and I have the same problem.
@sbalgas: Did you restart ST? GitGutter reads 'eol' setting only on startup at the moment.

**Comment by ssddanbrown** [comment] 2017-03-06 20:53
This issue popped up for me (ST3 / Ubuntu 16.10). `ignore_whitespace` worked for me after a restart. Thanks @deathaxe.

**Comment by atomtigerzoo** [comment] 2017-03-07 08:46
Thank you for your fast reaction :) Problem solved!

**Comment by JustRiedy** [comment] 2017-03-09 06:24
Adding  "ignore_whitespace": "eol", to settings solved the issue for me.

**Comment by deathaxe** [comment] 2017-03-18 09:41
Fix for the issue released with GitGutter 1.5.1

**Closed by deathaxe** 2017-03-18 09:41 UTC
Labels: bug

**Comment by gerardroche** [comment] 2017-05-08 13:53
@atomtigerzoo are you ignoring files on export in gitattributes file, see https://github.com/jisaacks/GitGutter/issues/409

**Comment by kikithedeveloper** [comment] 2017-06-16 03:39
Adding `"ignore_whitespace": "eol"` to my `GitGutter.sublime-settings - User` did not solve anything for me. All lines in certain files still show as modified after I just git pushed everything up to date. My gitgutter version is 1.7.2.

**Comment by deathaxe** [comment] 2017-06-16 08:06
The `"ignore_whitespace": "eol"` was proposed as I accidently removed the line-feed mangling in on of the older versions (1.5.0 I guess). 

> ... still show as modified ...

Really modified or green + signs?

> ... pushed everything up to date ...

Does it mean, you saved a modified file in ST, than staged and commited it using git from shell or one of ST's git packages like GitSavvy? And after all file is still displayed as modified?

Which git version do you use? Some user recently concerned about file modifications at the end of lines not being tracked correctly, which was finally caused by his old git version.

If you set `"debug": true` in the GitGutter.sublime-settings you'll maybe get some messages which could help to find the reason.
