### ISSUE TITLE
GitGutter hides SublimeLinter gutter marks

### ISSUE THREAD

**Issue by jeroentbt** [jisaacks/GitGutter#113] opened 2013-09-17 19:11 UTC
As it stands now, the GitGutter gutter marks hide the SublimeLinter gutter marks.
I would say that lint errors should take precedence here. Maybe you guys can work something out?

[SublimeLinter issue #554](https://github.com/SublimeLinter/SublimeLinter/issues/554)

**Comment by bridgesense** [comment] 2015-01-11 05:50
Glad to see I'm not the only one. :)  Gitgutter isn't playing well with SublimeLint or Xdebug

**Comment by Josh-a-e** [comment] 2015-02-17 10:11
Yes please :+1:

**Comment by jisaacks** [comment] 2015-02-25 04:05
> Well, I can confirm that Gitgutter-Edge has addressed these issues.

Its probably time to cut a new release.

**Comment by JerseyMilker** [comment] 2015-02-25 04:10
What is Gitgutter-Edge?

**Comment by jisaacks** [comment] 2015-02-25 04:16
> What is Gitgutter-Edge?

It is a seperate package that points directly to the `master` of git gutter instead of the latest release. You will get fixes faster, but not as stable.

**Comment by jisaacks** [comment] 2015-02-25 04:24
> Its probably time to cut a new release.

I just cut a prerelease but after reading Package Control's [prerelease section](https://packagecontrol.io/docs/settings#setting-install_prereleases) it looks like it probably will treat it as an official release.

**Comment by FichteFoll** [comment] 2015-02-25 13:27
@jisaacks, indeed. Package Control does not look at the "releases" page and does not look into your release or pre-release flagging there.

If you want to release a pre-release you need to use the pre-release section of [semver](http://semver.org) in your tag name, which would then look like `1.1.2-beta.1` or `1.2.0-rc.1`.

**Comment by jisaacks** [comment] 2015-02-25 13:38
Thanks @FichteFoll

**Comment by Zireael07** [comment] 2015-02-25 15:06
Can't wait to see a new release to be able to fix this problem.

**Comment by sebastienbarre** [comment] 2015-03-16 15:19
Love GitGutter, but love SublimeLinter too. Is protected_regions merged in GitGutter-Edge?
Thanks

**Comment by thalesfsp** [comment] 2015-03-28 19:57
Where's the solution?

**Comment by jonscottclark** [comment] 2015-04-22 16:41
Really excited to see a release soon. Thanks for getting it sorted out, @jisaacks !

**Comment by creativisionist** [comment] 2015-06-19 10:14
Installed GitGutter, tried to read and seemed like GitGutter-Edge found a resolution to overriding SublimeLinters.  Uninstalled GitGutter, installed GitGutter-Edge.  No resolution.  Uninstalled GitGutter-Edge, none of SublimeLinters work now.  Tried uninstalling and reinstalling SublimeLinters; same issue.  Gutter is completely back to default, no errors read.

Help?

**Comment by creativisionist** [comment] 2015-06-19 10:21
Installed GitGutter, tried to read and seemed like GitGutter-Edge found a resolution to overriding SublimeLinters. Uninstalled GitGutter, installed GitGutter-Edge. No resolution. Uninstalled GitGutter-Edge, none of SublimeLinters work now. Tried uninstalling and reinstalling SublimeLinters; same issue. Gutter is completely back to default, no errors read.

Help?

**Comment by jisaacks** [comment] 2015-06-19 13:20
@creativisionist have you looked at your preferences to make sure that `SublimeLinters` didn't accidentally get added to the ignored packages list?

**Comment by creativisionist** [comment] 2015-06-19 16:56
@jisaacks everything's enabled; only ignored pkg is "Vintage"

**Comment by jisaacks** [comment] 2015-06-19 17:04
@creativisionist have you tried completely shutting down sublime?

**Comment by creativisionist** [comment] 2015-06-19 18:03
Definitely.  Although after letting the computer rest for a bit seems at least one of the linters are working now (spec for my .scss files) but not all of them.  Have anytime by chance for a screen share?  I really would like to use both the linters and GitGutter ideally if possible.

**Comment by tboyce12** [comment] 2015-07-29 01:36
I disabled the GitGutter package. Now my more important gutter icons are showing up again. This is a great package, but not playing nice with others is a dealbreaker for me.

**Comment by FMCorz** [comment] 2015-08-07 03:06
+1. I would like to be able to set the priority, the linter flags are more important to me.

**Comment by madevelopers** [comment] 2015-08-23 14:49
Can't we set sublime to have a 2-column gutter? one column for git the other for linter?

**Comment by studenton** [comment] 2015-09-03 11:22
I'm facing the same problem. The gutter marks hides the sublimelinter gutter mark. Had to disable this plugin.

**Comment by hadees** [comment] 2015-09-30 20:23
It would actually be really cool if Git Gutter maybe showed an icon that both shows that the line changed and there is an error.  That way people know what errors they caused.

**Comment by studenton** [comment] 2015-10-01 03:37
Since the issue hasn't been fixed, I've switched to VCS Gutter. In that, the error gets the priority than the git gutter. If no errors are there, + sign is shown. Workaround for now until Gitgutter fixes this.

**Comment by jisaacks** [comment] 2015-10-07 18:32
OK if I can get some volunteers. I will merge #254 into master. So you would need to use GitGutter-EDGE, and if it fixes the problem, I will cut a release for GitGutter with it. Also would need to figure out what regions need to be protected and add them to the settings. In fact, if anyone could add a comment here with what those regions are, that would be greatly appreciated. Thanks.

**Comment by studenton** [comment] 2015-10-08 06:21
@jisaacks  I'm ready to help. I've installed GitGutter-EDGE. The problem is still there.

**Comment by jisaacks** [comment] 2015-10-08 13:07
@studenton I need to fix some conflicts, rebase and then merge the PR into master. Then you would need to make sure to update to the newer version. I will ping this thread at that time. Should be able to some time in the next couple days.

**Comment by studenton** [comment] 2015-10-08 13:56
Great!

**Comment by jisaacks** [comment] 2015-10-11 14:52
@studenton that PR is now merged into master.

**Comment by studenton** [comment] 2015-10-16 14:19
@jisaacks The issue is fixed. Thanks a lot for the fix.

**Comment by jisaacks** [comment] 2015-10-16 14:38
@studenton thanks for the feedback. What regions did you need to specify as protected for SublimeLinter? I would like to add it to the Read Me.

**Comment by studenton** [comment] 2015-10-16 14:53
@jisaacks Sorry I didn't quite get you about regions. I just installed the newest version of Gitgutter edge and sublimelinter is taking the priority than the gitgutter now. Errors are given preference instead of +. That's what we wanted.

**Comment by jisaacks** [comment] 2015-10-16 15:20
@studenton my lasted code add a setting for you to specify [protected regions](https://github.com/jisaacks/GitGutter/blob/master/GitGutter.sublime-settings#L58)

The icons in the gutter are placed there using named regions. GitGutter has specific names it gives the regions when it puts an icon there, SublimeLinter should as well.

With the latest code, before placing an icon, it will check to see if a region (from the specificed protected regions setting) already occupies that line. If so, git gutter will not put the icon there.

So if you did not specify protected regions, then my fix is not actually doing it's job and the fact that you are no longer seeing the issue is probably just coincidental or a race condition.

To determine which regions should protect you will either need to look at the SublimeLinter source code to see what they are naming them, or contact the authors and ask them.

Let me know if that clears it up :)

**Comment by studenton** [comment] 2015-10-16 16:20
Yup you're correct. It was just coincidental. I checked it again on different files and the issue arose again. Sorry for the confusion. @jisaacks.

**Comment by davicho** [comment] 2015-10-27 16:51
I must be missing something. Uninstalled GitGutter, installed GitGutter Edge but when I go to it's settings they are empty. I tired copying the settings from the repo online but didn't work. Am I missing a step?

**Comment by StyloBill** [comment] 2015-10-28 19:30
After a bit of testing, it appears that when you uninstall GitGutter then install it again, the two packages behave as intended (SublimeLinter takes priority over GitGutter) but if you then close Sublime Text and open it again, GitGutter takes back priority over Sublime Linter, which is bad.
Maybe @jisaacks could investigate this?
Thanks!

**Comment by davicho** [comment] 2015-10-28 20:23
@StyloBill I found the same behavior. I think it's a timing thing. SublimeLinter activates first and as soon GitGutter activates (which takes a bit longer), it overrides SublimeLinter.

**Comment by jisaacks** [comment] 2015-10-29 02:52
@davicho 

>  I go to it's settings they are empty.

How did you access the settings?

> copying the settings from the repo online but didn't work.

What didn't work?

**Comment by davicho** [comment] 2015-10-30 19:54
@jisaacks I uninstalled gitgutter via "remove package" interface in sublime and installed gitgutter-edge same way too.

Once gitgutter-edge was installed I tried to access the "protected regions" you are talking about BUT I could not find it under packages settings: sublime text>preferences>package settings>sublimelinter>settings (both Settings Default and Settings User are empty).

I tried copying and pasting this but no luck: https://github.com/jisaacks/GitGutter/blob/master/GitGutter.sublime-settings

Just trying to figure out how to enable protected regions.

**Comment by jisaacks** [comment] 2015-10-31 00:17
@davicho 

You said you went to:

>  sublime text>preferences>package settings>sublimelinter>settings

But you need to go to:

sublime text>preferences>package settings>__GitGutter__>settings

**Comment by davicho** [comment] 2015-10-31 15:17
@jisaacks 

so sorry... juggling both has had a bit brain fired. THAT is what I meant: 
sublime text>preferences>package settings>GitGutter>settings (both default and user settings are empty)

see: https://www.dropbox.com/s/j4svhj3mjsr84zr/Screenshot%202015-10-31%2011.14.44.png?dl=0

**Comment by develucas** [comment] 2015-11-11 17:33
I've tested fix from master branch and it seems it's working. I wish I had more time to do code review, the code requires optimization in my opinion.

After installing GitGutter-Edge add following to user settings

```"protected_regions": ["sublimelinter-error-gutter-marks", "sublimelinter-warning-gutter-marks"]```

Now someone should extend the list of region names by other names (e.g. for bookmarks - there is another related issue with icons) and update readme file.

We're almost there :)

**Comment by davicho** [comment] 2015-11-13 20:40
That works! Way to go @develucas!!! Cheers!

**Comment by wprater** [comment] 2015-12-22 06:32
it's also hiding my Xdebug breakpoint icons.  any fix in sight for that as well?

**Comment by jisaacks** [comment] 2015-12-23 05:59
I have cut a release with [protected regions](https://github.com/jisaacks/GitGutter#protected-regions) so I am closing this issue.

@develucas I added a section for protected regions to the README, however I wouldn't be opposed to having a section that also lists the region names for popular packages. If you wanted to make a PR and start that.

@wprater the [protected regions](https://github.com/jisaacks/GitGutter#protected-regions) feature fixes your issue as well.

**Closed by jisaacks** 2015-12-23 05:59 UTC

**Comment by wprater** [comment] 2015-12-23 07:06
@jisaacks thanks, how can one search for a region name in another plugin's codebase?

**Comment by wprater** [comment] 2015-12-24 02:37
@jisaacks the current line marker for xdebug will rarely show in a protected region.  I supposed this is because the file is not being modified, but the markers are being added.  thoughts for working around this?

**Comment by nfantone** [comment] 2016-01-02 16:32
I know this is an old (closed) issue, but since it had helped me solved my problem I wanted to say to everyone that comes along with the same problem [this is the solution](https://github.com/jisaacks/GitGutter/issues/113#issuecomment-155855888). `README.md` tells you, in a rather obscure way, to "figure out the name of the `protected_regions`. Those names are provided in the linked comment of @develucas.

**Comment by jisaacks** [comment] 2016-01-03 01:30
> README.md tells you, in a rather obscure way, to "figure out the name" of the protected_regions

That is because SublimeLinter is not the only package that may have conflicts. So it is up to the user to __figure out__ what region names to protect. And like I said before, I have no problem listing common ones if someone wants to make a PR.

**Comment by nfantone** [comment] 2016-01-03 19:20
@jisaacks Yes, I was aware of that. I read your first comment. But you can't deny that for first comers, regular Sublime/git users or even advanced users with no or little previous knowledge of how the package works (which is most of us here, I tend to think) reading something like "go figure out some random strings that my python script likes" it's pretty vague and **will** get them lost. That's a given.

I myself, have been using Sublime for years, and have no idea what a _"region"_ is or why it needs _"protection"_ of any kind. Perhaps I'm the only confused and/or ignorant person around. If that's the case, I apologize. I just wanted to help people struggling with the same problem I was having.

**Comment by jisaacks** [comment] 2016-01-05 19:32
@nfantone you have a valid point, please make a PR with how you think it could be better explained.

**Comment by nfantone** [comment] 2016-01-05 20:25
@jisaacks Sure thing. I'd love to do that. Thing is, I really don't know the explanation that needs to be written. That's the reason I ended up here and stumble upon this issue. 

If you could kindly explain me what a protected region is and how to figure out its name, I'll prepare the PR -- though, I fear that if you do that, you'll be writing the proper README.md yourself. So, maybe, I'm not the most suited person to do it.

**Comment by jisaacks** [comment] 2016-01-07 20:34
@nfantone in order to place an icon in the gutter, you must do so via a region in sublime text. Here is the API for it:

```
view.add_regions(key, [regions], <scope>, <icon>, <flags>)
```

You can read more about at https://www.sublimetext.com/docs/3/api_reference.html

When you add regions, along with the optional __icon__ you must give a key aka a ___name___.

So this means any package that places icons in the gutter must be doing it via a region, and that region must have a name.

Here is where git gutter does it: https://github.com/jisaacks/GitGutter/blob/master/git_gutter.py#L149

So if you specify the names of the regions you do not want git gutter to override. It can check if that region is there before putting an icon there. But the user unfortunately must go dig through the packags source to find the region names, something I do not wish to do. It would be nice if the package authors listed them in the read me.

I hope that helps.

**Comment by jisaacks** [comment] 2016-01-07 20:41
In fact, I wouldn't even be apposed to having some presets like 
```javascript
"protected_regions_presets" : ["SublimeLinter", "BracketHighlighter"]
```
That evaluate to a saved list or region names used by those packages.

But someone would need to maintain those lists.

**Comment by yaroslavyaroslav** [comment] 2016-01-09 01:50
If someone helps, this is regions for anaconda linting:
"protected_regions": ["ERRORS", "ERRORS", "WARNINGS", "WARNINGS", "VIOLATIONS", "VIOLATIONS"],

**Comment by jisaacks** [comment] 2016-01-09 21:34
@yaroslavyaroslav it would be unwise for a package to not prefix their region names with their package name.

**Comment by yaroslavyaroslav** [comment] 2016-01-09 23:11
@jisaacks Here's the region name  anaconda-master/anaconda_lib/jediusages.py:
105: region_name = 'anaconda.indicator.{}.{}'.format(self.text.view.id(), lineno)

So the first part is "anaconda.indicator", but it seems that in braces  are unique numbers. What can be done with this?

**Comment by xeroxoid** [comment] 2016-01-29 10:46
Also for anyone (like me) having a problem with GitGutter overlapping JSHint errors, I found the region code in [JSHint Gutter code](https://github.com/victorporof/Sublime-JSHint/blob/8c13bc62d352fdaa313c93ccaf0b1a7a70a771af/JSHint.py).

This will fix it (even on stable GitGutter release):
`"protected_regions": ["jshint_errors"]`

*flies away*

**Comment by timkuijk** [comment] 2016-02-11 17:52
For GitGutter overlapping [Phpcs](https://github.com/benmatselby/sublime-phpcs/blob/master/phpcs.py#L508) errors I had to add "checkstyle" to protected_regions in addition to what @develucas suggested. If you also need the JSHint fix from @xeroxoid it all comes down to: 

`"protected_regions": ["jshint_errors", "checkstyle", "sublimelinter-error-gutter-marks", "sublimelinter-warning-gutter-marks"]`

**Comment by jadatkins** [comment] 2016-02-19 10:37
The protected regions for SublimeLinter that are working for me are as follows. (First open Preferences > Package Settings > GitGutter > Settings – User. Then paste this in. Save and restart SublimeText.)

```json
{
  "protected_regions": [
    "sublimelinter-warning-marks",
    "sublimelinter-error-marks",
    "sublimelinter-warning-gutter-marks",
    "sublimelinter-error-gutter-marks",
  ],
}
```

**Comment by pirate** [comment] 2016-02-25 22:54
@jadatkins That worked for me, thanks!  Is there an equivalent region name for Sublime Bracket Highlighter like `brackethighlighter-brackets`?

**Comment by jadatkins** [comment] 2016-02-26 10:19
@pirate I have no idea. I don't use that.

**Comment by jisaacks** [comment] 2016-02-26 13:40
@pirate you can either contact the author of that package or rummage through the source code. If you figure it out, please post back. Hopefully we can get a list of the common ones.

**Comment by pirate** [comment] 2016-02-26 19:55
Found them after a bit of digging in the [bracket highlighter repo](https://github.com/facelessuser/BracketHighlighter/blob/master/bh_regions.py).  Here are all the Sublime Bracket Highlighter region keys, edit the list to suit your personal preferences.
```python
>>>view.settings().get('bh_regions')
['bh_tag', 'bh_tag_center', 'bh_tag_open', 'bh_tag_close', 'bh_tag_content', 'bh_double_quote', 'bh_double_quote_center', 'bh_double_quote_open', 'bh_double_quote_close', 'bh_double_quote_content', 'bh_single_quote', 'bh_single_quote_center', 'bh_single_quote_open', 'bh_single_quote_close', 'bh_single_quote_content', 'bh_curly', 'bh_curly_center', 'bh_curly_open', 'bh_curly_close', 'bh_curly_content', 'bh_square', 'bh_square_center', 'bh_square_open', 'bh_square_close', 'bh_square_content', 'bh_round', 'bh_round_center', 'bh_round_open', 'bh_round_close', 'bh_round_content', 'bh_default', 'bh_default_center', 'bh_default_open', 'bh_default_close', 'bh_default_content', 'bh_c_define', 'bh_c_define_center', 'bh_c_define_open', 'bh_c_define_close', 'bh_c_define_content', 'bh_regex', 'bh_regex_center', 'bh_regex_open', 'bh_regex_close', 'bh_regex_content', 'bh_angle', 'bh_angle_center', 'bh_angle_open', 'bh_angle_close', 'bh_angle_content', 'bh_unmatched', 'bh_unmatched_center', 'bh_unmatched_open', 'bh_unmatched_close', 'bh_unmatched_content']

```

Here are my final GitGutter settings after adding these along with the SublimeLinter regions:
```json
{
    "protected_regions": [
        "sublimelinter-warning-marks",
        "sublimelinter-error-marks",
        "sublimelinter-warning-gutter-marks",
        "sublimelinter-error-gutter-marks",
        "bh_tag",
        "bh_tag_center",
        "bh_tag_open",
        "bh_tag_close",
        "bh_tag_content",
        "bh_double_quote",
        "bh_double_quote_center",
        "bh_double_quote_open",
        "bh_double_quote_close",
        "bh_double_quote_content",
        "bh_single_quote",
        "bh_single_quote_center",
        "bh_single_quote_open",
        "bh_single_quote_close",
        "bh_single_quote_content",
        "bh_curly",
        "bh_curly_center",
        "bh_curly_open",
        "bh_curly_close",
        "bh_curly_content",
        "bh_square",
        "bh_square_center",
        "bh_square_open",
        "bh_square_close",
        "bh_square_content",
        "bh_round",
        "bh_round_center",
        "bh_round_open",
        "bh_round_close",
        "bh_round_content",
        "bh_default",
        "bh_default_center",
        "bh_default_open",
        "bh_default_close",
        "bh_default_content",
        "bh_c_define",
        "bh_c_define_center",
        "bh_c_define_open",
        "bh_c_define_close",
        "bh_c_define_content",
        "bh_regex",
        "bh_regex_center",
        "bh_regex_open",
        "bh_regex_close",
        "bh_regex_content",
        "bh_angle",
        "bh_angle_center",
        "bh_angle_open",
        "bh_angle_close",
        "bh_angle_content",
        "bh_unmatched",
        "bh_unmatched_center",
        "bh_unmatched_open",
        "bh_unmatched_close",
        "bh_unmatched_content",
    ],
}
```

**Comment by jisaacks** [comment] 2016-02-27 05:12
@pirate thats strange. I read through the issue you opened and I agree it must be one of the two situations you mentioned.

If you want to install GitGutter via git you can modify the code that [checks for protected regions](https://github.com/jisaacks/GitGutter/blob/master/git_gutter.py#L90) and with some debugging (basically manually determine what region BH has used and see if it is in the list being checked by GitGutter) may lead to some answers.

**Comment by pirate** [comment] 2016-02-27 05:51
Thanks for linking straight to the line I needed :).  I ran some tests and found that function works exactly as expected when run from console, but gets an empty list of rendered `by_curly_open` regions when run from inside GitGutter, which leads me to believe @facelessuser is right, it is possible that GitGutter is running this function before BH renders.

<img width="484" alt="screen shot 2016-02-26 at 9 50 54 pm" src="https://cloud.githubusercontent.com/assets/511499/13371104/0b3ba914-dcd3-11e5-958c-b07e04b24baf.PNG">

**Comment by kylebebak** [comment] 2016-03-09 07:38
@jadatkins adding these `protected_regions` worked great for me for about a week, and then suddenly it regressed and GitGutter started overwriting SublimeLinter again.

I'm not sure why. Maybe a recent update to SublimeLinter changed the names of the protected regions. In any case, adding more `protected_regions` has solved the problem again for me.

~~~json

  "protected_regions": [
    "sublimelinter-warning-marks",
    "sublimelinter-error-marks",
    "sublimelinter-warning-gutter-marks",
    "sublimelinter-error-gutter-marks",
    "lint-underline-illegal",
    "lint-underline-violation",
    "lint-underline-warning",
    "lint-outlines-illegal",
    "lint-outlines-violation",
    "lint-outlines-warning",
    "lint-annotations",
  ]

~~~

**Comment by jmrd98** [comment] 2016-04-29 20:45
For the Anaconda package: `"protected_regions": [
  						"anaconda-lint-outlines-illegal", 
  						"anaconda-lint-outlines-warning", 
  						"anaconda-lint-outlines-violation"
  	`
Just as a reference to anyone arriving via google. Pertinent code in Anaconda [here](https://github.com/DamnWidget/anaconda/blob/2a4a3e67a6870346e855c916a380dfa7aa71f498/anaconda_lib/linting/sublime.py#L228), line 228 as of the time of writing.

**Comment by TimZaman** [comment] 2016-07-22 13:14
`protected_regions` functionality works great, thanks.
