### ISSUE TITLE
Bookmark icon is covered by Gutter

### ISSUE THREAD

**Issue by jiyinyiyong** [jisaacks/GitGutter#76] opened 2013-03-21 06:02 UTC
Might be not really a bug though,..
If I try adding bookmark in the same line where Gutter highlights, there would be no response of bookmarks. I suppose the space at a line start can only hold one icon. While there are two, they just conflct.
Then there's a problem: I can't tell from the line wether there's a bookmark, that's annoying.

**Comment by sundarv85** [comment] 2015-11-06 11:02
+1 here. Any update on this.

**Comment by jisaacks** [comment] 2015-11-06 16:11
I merged the `protected-regions` branch into master. However, I am trying to get people to test it out and report back to me (using GitGutter-EDGE) before I cut a release. Unfortunately, I haven't had a report of a single user installing and using protected-regions.

**Comment by develucas** [comment] 2015-11-11 17:33
I've tested your fix in the context of SublimeLinter and it seems it's working. I wish I had more time to do code review, the code requires optimization in my opinion.

After installing GitGutter-Edge add following to user settings

```"protected_regions": ["sublimelinter-error-gutter-marks", "sublimelinter-warning-gutter-marks"]```

Now someone should extend the list of regions by bookmarks etc and update readme file.

**Comment by jisaacks** [comment] 2015-11-11 19:23
Thanks @develucas!!

**Comment by jisaacks** [comment] 2015-11-11 19:29
Thanks @develucas, what optimizations were you thinking?

**Comment by g105b** [comment] 2016-04-24 12:59
Hi all. I have been following this thread for a while as I use Sublime Linter and XDebug (which places debug breakpoints in the gutter).

Tried multiple things over the past weeks to avoid having GitGutter eat up the gutter icons, and today I tried removing Githutter completely and installing manually.

After installing manually (cloning the repo into the Packages directory), Gitgutter no longer takes preference over the other gutter icons!

So whatever you've changed works. But please note that GitGutter-Edge still has the issue for me (Ubuntu 15.10 64bit).

**Comment by g105b** [comment] 2016-06-01 13:54
I'm back. GitGutter has started drawing gutter icons over the top of the bookmarks and sublime linter / xdebug breakpoint indicators.

This issue is still open for me. Here's the contents of my GitGutter.sublime-settings (which makes no difference):

```
{
	"protected_regions": [
		"sublimelinter-warning-marks",
		"sublimelinter-error-marks",
		"sublimelinter-warning-gutter-marks",
		"sublimelinter-error-gutter-marks",
		"lint-underline-illegal",
		"lint-underline-violation",
		"lint-underline-warning",
		"lint-outlines-illegal",
		"lint-outlines-violation",
		"lint-outlines-warning",
		"lint-annotations",
	]
}
```

**Comment by sentience** [comment] 2016-06-07 02:50
Likewise, the `protected_regions` setting is not working for me. SublimeLinter gutter icons are being overridden with GitGutter gutter icons, despite my having specified:

```
{
  "protected_regions": [
    "sublimelinter-warning-gutter-marks",
    "sublimelinter-error-gutter-marks"
  ]
}
```

**Comment by ocrow** [comment] 2016-10-20 05:19
GitGutter.sublime-settings has the following, but bookmark icons are still overridden by GitGutter. 
Is this feature working?

```
  "protected_regions": [
    "sublimelinter-warning-gutter-marks",
    "sublimelinter-error-gutter-marks",
    "bookmarks"
  ]
```

**Comment by r-stein** [comment] 2016-10-20 07:17
@ocrow Do you use the normal bookmarks or have a bookmark package? Normal bookmarks should work and works for me.

**Comment by ocrow** [comment] 2016-10-20 21:51
I'm using normal bookmarks. SublimeText 3126; GitGutter v1.3.0.

**Comment by r-stein** [comment] 2016-10-21 07:48
@ocrow How does the line look like and where do you add a bookmark? The region detection should work for the whole line with https://github.com/jisaacks/GitGutter/pull/304, but might still have some flaws.

**Comment by ocrow** [comment] 2016-10-21 20:44
I see a small greenish square in the first column to the left of the line number of any line that has been modified since the last commit. If I add a bookmark on a line that _has not_ been edited, it appears as a large white right-pointing triangle arrow. 

If I add a bookmark on any line that _has_ been edited, the white bookmark arrow does not appear, which is the problem. It does not make any difference whether the bookmark is at the beginning of the line, the end of the line, or in the middle of the line. Similarly the bookmark may be for a single position or a selection. In each case the bookmark icon does not appear iff the start of the bookmark is within a line that was already marked by GitGutter as edited.

If I add a bookmark before editing the line, the bookmark arrow stays and the 'modified' square does not appear. I think that is expected behavior.

**Comment by ocrow** [comment] 2016-10-26 01:23
I removed my GitGutter user configuration, uninstalled & reinstalled GitGutter, restarted SublimeText, and all of that seems to have done the trick. I now can see bookmarks on top of GitGutter modified icons.

**Comment by r-stein** [comment] 2016-10-26 19:10
@ocrow Good that it works now =)

Also this whole issue should be fixed and I close it.

**Closed by r-stein** 2016-10-26 19:10 UTC

**Comment by g105b** [comment] 2016-10-27 09:59
Activity on this thread made me try Gitgutter again after a long time. Worked really nicely at first, but it seems like I have to remove and reinstall Gitgutter multiple times per week to maintain consistent behaviour with bookmarks.

**Comment by r-stein** [comment] 2016-10-27 10:36
@g105b reinstalling GitGutter does not change the code, so it's weird that this would fix something. If you can provide reproducable examples where it fails, I would be glad to fix those.

**Comment by g105b** [comment] 2016-10-27 10:37
Will do - I'll keep my eye on it. Is there any logging I can turn on so I can provide these as soon as I notice gitgutter going over the top of bookmarks?

**Comment by r-stein** [comment] 2016-10-27 10:55
There is no logging command and this is more about overlapping regions. You can paste this into the ST console and it should output all relevant informations about regions and lines:

``` py
region_names = ["bookmarks"] + ["git_gutter_" + r for r in ['deleted_top', 'deleted_bottom', 'deleted_dual', 'inserted', 'changed', 'untracked', 'ignored']]; [("lines", view.lines(sublime.Region(0, view.size())))] + [(r, view.get_regions(r)) for r in region_names]
```

In addition it would be nice if you could provide a small description in which order you have added the boomarks and the gitgutter informations.

**Comment by g105b** [comment] 2016-10-27 12:19
Roger that. Will reply back when the problem happens again. Still working fine today.

**Comment by redochka** [comment] 2016-12-05 19:39
Problem still there. Please check

**Comment by jhakonen** [comment] 2017-04-05 15:26
I seem to have the same problem. Seems to be working partially in my case.

This works as expected:
1. Add a bookmark to a line, bookmark icon (white right pointing arrow) appears on the line
2. Modify the same line, bookmark icon remains, as expected

However, this does not:
1. Modify a line, GitGutter's changed icon (yellow square) appears
2. Add a bookmark on the same line, changed icon remains, should have changed to bookmark icon, but did not.

Workaround:
Modify another line, changed icon appears. At same time the previous line's icon updates from GitGutter's changed icon to bookmark icon.

Using ST3 3126, GitGutter 1.5.1.

**Comment by deathaxe** [comment] 2017-04-05 17:23
GitGutter can't track other plugins adding or removing gutter icons and thus can't react on it. It only checks for existing gutter icons (protected_regions), if it is about to update its own gutter icons.

It is an intended behavior of GitGutter so far to update its gutter icons only, if either the view's content or the file from database has changed. The whole evaluation is aborted, if none of the files has changed to not unnecessarily run git and/or write file content repetitively to disk.

Anyway, adding/removing bookmarks doesn't trigger any event, which would cause icons to update. A view must be (loaded, cloned), activated or modified to trigger GitGutter to evaluate changes.

**Comment by r-stein** [comment] 2017-04-05 17:41
It is very weird that it overwrites "added" and "deleted" icons, but not "changed" icons. We should have a look into the reason for that and try to adapt our way of adding the "changed" icons accordingly. It may have to do something with the name or the icon path.

**Comment by deathaxe** [comment] 2017-04-05 17:56
The reason is, that the bookmark icon is simply added to the line, where a GitGutter icon already exists. So they fight against each other - maybe by name - and GitGutter seems to win sometimes. All GitGutter region names start with "git_gutter_" so I don't have an idea, why bookmarks should have a "priority" in between of "added/deleted" and "changed" regions. The only possible reason would be ST sorting by 'scope' name but not 'region_name'. The scopes are named like 'markup.added.git_gutter'. I'll have a look on it, but won't change scope names because of backward compatibility.

The only way was to check when one of the protected regions has changed and update gutter icons to avoid fighting. :-/ Some kind of messy.

**Comment by r-stein** [comment] 2017-04-05 18:07
You could also name the scope `aaaaa, markup.inserted.git_gutter` to keep backward compat. One could also create an EventListener to refresh the git gutter regions after some commands are executed.

``` py
import sublime_plugin


class BookmarkGitgutterListener(sublime_plugin.EventListener):
    def on_post_text_command(self, view, command_name, args):
        if command_name == "toggle_bookmark":
            view.window().run_command("git_gutter") # not sure which arguments to pass to refresh the icons
```

**Comment by deathaxe** [comment] 2017-04-05 18:52
This might address the problem with bookmarks, but we would need something to work for all `protected_regions` - just to keep consistent. As a user can define its own list of regions, this might be a quite tricky task.
