### ISSUE TITLE
git binary lost after upgrade to 1.2.4

### ISSUE THREAD

**Issue by okote** [jisaacks/GitGutter#305] opened 2016-08-23 17:06 UTC
Hi,

After the automatic upgrade from 1.2.3 to 1.2.4, I got the message:
`Your Git binary cannot be found.  If it is installed, add it to your PATH environment variable, or add a 'git_binary' setting in the 'User/GitGutter.sublime-settings' file.`
which never happened to me with previous versions.

I fixed it following the instructions, but it may be a problem for some users. It may be a symptom of other issues, though. I'm using the default git at `/usr/bin/git` in a macOS Sierra (beta 6), with ST2 2.0.2 (2221).

Cheers,

Nicolás

**Comment by degamer106** [comment] 2016-08-23 18:09
Same here.  Don't know what changed.  I'll try the instructions as well.  

I'm running Sublime Text 2 + this plugin on OSX 10.11.6 if that helps.

**Comment by jisaacks** [comment] 2016-08-23 18:40
Prior to the new version if GitGutter could not find your `git` binary it would silently fail. Now it shows this warning.

**Comment by okote** [comment] 2016-08-23 18:42
But *it was* able to find it before. I've been using GitGutter for months, without problem.

**Comment by r-stein** [comment] 2016-08-23 18:45
I think the problem is that it uses `shutils.which` on ST3, which is not available in ST2. However one could run a manual search for the executable.

**Comment by mccarthy** [comment] 2016-08-26 14:14
This is not working as intended.  For me, the git binary is at `/usr/local/bin/git`, and is in my PATH, but I am still seeing this error message.  

I'm on:
ST 2.0.2 Build 2221
OSX 10.10.5
GitGutter 1.2.4

**Comment by r-stein** [comment] 2016-08-26 16:21
Might be a good idea to merge and release https://github.com/jisaacks/GitGutter/pull/306 as a Bugfix before the next bigger release.

**Comment by rchl** [comment] 2016-11-15 21:17
@mccarthy It's in the PATH of your terminal but probably not of the Sublime. Since some time OSX is quite restrictive on regarding which environment variables GUI applications inherit. You probably would have to install something like https://github.com/int3h/SublimeFixMacPath to make Sublime find git from `/usr/local/bin/git` automatically.

**Comment by rchl** [comment] 2016-11-15 21:17
And #306 was merged so I think there is resolved now.

**Closed by rchl** 2016-11-15 21:17 UTC

**Comment by Roman1972** [comment] 2016-12-20 19:06
REMOVE GitGutter And everything goes !!!
