### ISSUE TITLE
Command to show annotations on demand

### ISSUE THREAD

**Issue by mwean** [jisaacks/GitGutter#535] opened 2019-02-06 01:39 UTC
## Description

I would like the annotation feature exposed as a command so it can be shown on-demand with a shortcut. I don't like having it on all the time because it's distracting most of the time, but I'd like to be able to blame a line (or multiple?) with a shortcut. It seems like we could just update `run_blame` to have an argument that would bypass the `git_gutter.line_annotation.is_enabled()` check. Does that sound reasonable?

**Comment by deathaxe** [comment] 2019-02-06 17:04
The `run_blame` basically was intended to be used as command. Binding it to the settings, which are needed for the event handling is actually an oversight. It should work the same way as the `show_diff_popup`.

Don't think it makes much sense to run blame on multiple lines at a time. Handling that would need much more effort to parse git's results. Displaying tons of blame messages at the end of a line would be confusing anyway. The annotation is just meant for a quick info. For anything else GitSavvy's blame or Sublime Merge's blame function are much more suitable.

**Comment by AmjadHD** [comment] 2019-02-07 20:09
is there currently a way to disable icons ?

**Comment by deathaxe** [comment] 2019-02-07 20:27
A first step was taken in the most recent commit on master, but it does work properly with Compare Against HEAD at the moment. Need to make use of ST's `set_reference_document()` API to keep the mini diff in sync if an older revision is selected via _Compare Against...._

**Comment by deathaxe** [comment] 2019-03-13 19:35
Fixed in 1.10.0

**Closed by deathaxe** 2019-03-13 19:35 UTC
Labels: enhancement
