### ISSUE TITLE
shutil errors

### ISSUE THREAD

**Issue by chere005** [jisaacks/GitGutter#301] opened 2016-08-15 18:33 UTC
Traceback (most recent call last):
  File "./git_gutter_events.py", line 74, in callback
  File "./view_collection.py", line 20, in add
  File "./git_gutter_handler.py", line 20, in __init__
  File "./git_gutter_handler.py", line 285, in load_settings
AttributeError: 'module' object has no attribute 'which'

Traced it to line 285 in git_gutter_handler.py, attempting to call shutil.which(), but that function doesn't work with Python 2, which is the version my sublimetext2 was using. Let me know if you need any other info.. OSX 10.11.5

I worked around the issue by hardcoding self.git_binary_path to usr/bin/git

**Comment by chere005** [comment] 2016-08-15 20:03
It eventually stopped working again with new errors.. setting the git binary path in the settings appears to have fixed my problem, but I've been using GitGutter for several months and it has always automatically worked, and only required me to set this as of last week. I'm not sure why it stopped working, though it appears to be line 284 in commit 5e8f2f28d5666bd74715d58717bcda943757577d

**Comment by chere005** [comment] 2016-08-15 20:04
new errors 

OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./git_gutter.py", line 34, in run
  File "./view_collection.py", line 55, in untracked
  File "./git_gutter_handler.py", line 183, in untracked
  File "./git_gutter_handler.py", line 199, in handle_files
  File "./git_gutter_handler.py", line 264, in run_command
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception

**Comment by jisaacks** [comment] 2016-08-16 19:09
Thanks for reporting. Closing as duplicate of #298

**Closed by jisaacks** 2016-08-16 19:09 UTC
