### ISSUE TITLE
Option to disable gutter icons

### ISSUE THREAD

**Issue by schrodincat** [jisaacks/GitGutter#538] opened 2019-03-13 18:08 UTC
Sublime Text 3.2 just released and [it implements some of the functionality](https://www.sublimetext.com/docs/3/git_integration.html) from this package in the editor itself. We are talking about:

1. Git gutter icons.
2. Markers for untracked files in the project tree.
3. General repo info in the status bar.

I would love to use both implementations simultaneously since this packages has awesome functionality like custom line annotations and custom status bar text. But currently there is no way to hide git gutter icons provided by this packages which as a result looks like this in 3.2:

<img width="144" alt="Screenshot 2019-03-13 at 20 58 12" src="https://user-images.githubusercontent.com/13354491/54303154-71224c80-45d3-11e9-8a9a-8e8c4a223ba3.png">

Unfortunately, new Sublime Text git integration doesn't provide granular control for different features. User can only toggle it on/off completely.

I would like to have an option to disable git gutter icons, something like `show_gutter_icons` and similar in it's behaviour to other granular on/off options provided by this package.

**Comment by michaelblyons** [comment] 2019-03-13 18:32
Possible duplicate of #537?

**Closed** 2019-03-13 19:27 UTC

**Comment by deathaxe** [comment] 2019-03-13 19:40
Fixed in 1.10.0
