### ISSUE TITLE
Getting GitGutter to work with remote files

### ISSUE THREAD

**Issue by jwogrady** [jisaacks/GitGutter#151] opened 2014-03-11 20:51 UTC
I am having trouble getting GitGutter to work; probably because of my unique setup.

I am using Windows 8.1 to run Sublime Text 3.

My dev files are hosted on a Linux machine. (Raspberry File running Raspian/Samba)

On Windows, I've mapped a drive to my Linux Git binary.

My setting file looks like this..

{
  // Custom path to git binary when not in PATH
  "git_binary": "R:\usr\bin\git"

}

I don't get any errors. Just don't see the icons in the gutter.

I've tried on ST2 and get the same result.

Thanks for all your hard work on this plugin. I've used it for a while now and really like it.

update:

As a workaround, I installed Git on Windows and added it to my Win Sys PATH.  It works.  Prefer to use the same version of Git on the dev server though....

**Comment by rchl** [comment] 2016-11-12 10:02
As said, this is not a bug. Closing.

**Closed by rchl** 2016-11-12 10:02 UTC
