### ISSUE TITLE
GitGutter running on non-repository files

### ISSUE THREAD

**Issue by JonathanHolvey** [jisaacks/GitGutter#266] opened 2016-02-11 07:32 UTC
I've noticed that GitGutter still sets the status bar string `Comparing aginst: HEAD` even if the current file isn't in a Git repository.

**Comment by jisaacks** [comment] 2016-02-12 17:22
Thanks for reporting. yeah #267 would most likely be the same bug/fix. There is a check for the `.git` folder, there probably just needs to be a way to short circuit and not draw or saw anything in the case it is not found.

**Comment by rchl** [comment] 2016-11-15 21:34
Yep, will close as duplicate of #267.

**Closed by rchl** 2016-11-15 21:34 UTC
Labels: duplicate
