### ISSUE TITLE
GitGutter 1.7.0 breaks compatibility with git v2.10 and oldler by using git cat-file --filters

### ISSUE THREAD

**Issue by zachleigh** [jisaacks/GitGutter#416] opened 2017-05-29 00:18 UTC
Just upgraded to 1.7.0. Was working perfectly before, but now get a green plus in all lines, regardless of git changes. Have restarted Sublime several times.    

Sublime Text version 3126    
Ubuntu 16.04

**Comment by nskazki** [comment] 2017-05-29 00:29
@zachleigh I have the same issue. Fix just for now:
```bash
cd ~/.config/sublime-text-3/Packages
git clone --branch 1.6.0 git://github.com/jisaacks/GitGutter.git
```
Also, I first uninstall GitGutter via package manager, but I'm not sure if this is really required.

```
git version 2.7.4
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Sublime Text Build 3126
Ubuntu 16.04
```

**Comment by zachleigh** [comment] 2017-05-29 00:39
@nskazki Thanks for that. Seems to be back to normal.

**Comment by ehansen486** [comment] 2017-05-29 00:42
Thank you, this has been driving me crazy the last half hour!

**Comment by Soulsbane** [comment] 2017-05-29 00:43
Same problem here.

**Comment by vdwees** [comment] 2017-05-29 01:21
Same problem here.
Sublime Text version 3126
Ubuntu 16.04

**Comment by leongaban** [comment] 2017-05-29 01:30
I still get this problem, nskazki's fix did not work for me :( Also I don't have that folder. I installed the older package into my application support folder.

**Comment by glennr** [comment] 2017-05-29 02:04
This worked for me (on OSX)

I manually removed the installed (latest) package, then downgraded using @nskazki 's method, but with a different (default) folder

```
rm ~Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/GitGutter.sublime-package
cd /Library/Application Support/Sublime\ Text\ 3/Packages/
git clone --branch 1.6.0 git://github.com/jisaacks/GitGutter.git
```

**Comment by taufnrsyd** [comment] 2017-05-29 03:31
@glennr doesn't work for me, it's still showing the green plus icon. Does Sublime Text force update the package?

Sublime Text build 3126
OS X 10.12.5

**Comment by taufnrsyd** [comment] 2017-05-29 03:40
Oh my bad, I was cloning to `Installed Packages` instead of `Packages` directory. @glennr's solution works for OSX. Thanks!

**Comment by alecive** [comment] 2017-05-29 04:01
Same problem here. @jisaacks any chance of having it fixed in the version from the package manager?

**Comment by pixilation** [comment] 2017-05-29 04:58
I tracked this issue down to commit 4a95320.
This commit started using the git command `git cat-file --filters`.
However the --filters argument wasn't added until git v2.11.0 (https://github.com/git/git/commit/b9e62f60115c75c5be5de593862925c8b8d7e683)
I upgraded git from v1.9.5 to v2.13.0 and this issue went away.

**Comment by yoonwaiyan** [comment] 2017-05-29 06:00
For my OSX Yosemite, @glennr 's or @pixilation 's solution doesn't work when using either of it separately, but after both upgrading my git from 2.8 to 2.13 AND re-installed GitGutter it worked. 

In case anyone wants to copy and paste @glennr 's solution, Sublime packages are stored in home directory's Library/Application Support.

**Comment by glennr** [comment] 2017-05-29 06:04
Yeah - sorry - updated my example to use the correct paths relative to $HOME

**Comment by Soulsbane** [comment] 2017-05-29 06:05
Upgrading git to 2.13.0 fixed my issue. Used this [PPA](https://launchpad.net/~git-core/+archive/ppa)
Commands for those interested:
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git

**Comment by shivi74** [comment] 2017-05-29 07:19
@Soulsbane Worked. Thanks!

**Comment by agungyuliaji** [comment] 2017-05-29 08:00
thanks @Soulsbane , upgrading git worked!!!!
also for macosx, need add this configuration on GitGutter config :
`
{
  "git_binary": "/usr/local/bin/git"
}
`
since i use git from brew
default is => `"git_binary": "/usr/bin/git"`

**Comment by RafalSkolasinski** [comment] 2017-05-29 08:08
@r-stein, thanks for pointing me to this issue.

However, not many distros there come with version 2.11 of ``git`` out of a box. 

Fedora 25: 2.9.4
Ubuntu 16.04 (LTS): 2.7.4
Debian Jessie: 2.1.4

Maybe there could be way to workaround it without requesting people to upgrade their git?

**Comment by r-stein** [comment] 2017-05-29 09:37
@RafalSkolasinski I fully agree with that https://github.com/jisaacks/GitGutter/issues/395#issuecomment-290784283 . We should 
- check for the git version
- only add the flags if they are supported
- support down to the lowest version, which is used by popular package managers
- at least inform the user if his version is not supported anymore
- favor compatibility over speed/minor improvements

I don't think requiring version 2.11 (by changing the flag) was intentional, but nobody reported it in the beta-tests/pre-releases.

**Comment by ArtemBernatskyy** [comment] 2017-05-29 09:45
Same issue !!!

**Comment by evasquez26** [comment] 2017-05-29 10:38
Same issue, thanks @Soulsbane it worked, I'm on Ubuntu Ubuntu 16.10

**Comment by yoavmmn** [comment] 2017-05-29 11:12
@r-stein is right. version 2.11 isn't available yet for Fedora 25 through the official repos and I guess that's the same on other distros.

**Comment by stratakis** [comment] 2017-05-29 12:37
Fedora users can upgrade git to 2.11 through this (unofficial) repository:

https://copr.fedorainfracloud.org/coprs/churchyard/git/

**Comment by nils-m** [comment] 2017-05-29 12:47
Holy moses thanks @nskazki
On debian Jessie v. 2.11 is in testing. I prefer downgrading gitgutter for now
And waiting for a fix !

**Comment by lombervid** [comment] 2017-05-29 15:24
@Soulsbane Worked for me to. Thanks!! :+1:

**Comment by chubatov** [comment] 2017-05-29 15:53
@nskazki It's work ). Thanks!

**Comment by fcpauldiaz** [comment] 2017-05-29 16:48
upgrading git didn't worked for me.

**Comment by madyaneka** [comment] 2017-05-29 16:50
It works! Thank you @Soulsbane :)

**Comment by gfauredumont** [comment] 2017-05-29 17:00
Same issue here.
Sorry for maintainer(s) but I'm going for the GitGutter downgrade (thanks @nskazki !) instead of manually upgrading to a new major version of Git on the spot: feels safer ;)

**Comment by deathaxe** [comment] 2017-05-29 17:48
**Damn!**

GitGutter started to use `git cat-file --filters` in order to fix Issue #409 which caused files being export-ignored in .gitattributes to appear as inserted. The `--filters` argument is required in order not to reintroduce Issue #74 which was the reason for issue #409. 

> However the --filters argument wasn't added until git v2.11.0 (git/git@b9e62f6)

Sorry, but I actually was not aware of that.

- Removing it will break support for **smudge filters** (issue #74)
- Reverting to `git archive` will cause export-ignored files to be displayed as inserted again (issue #409)

**There is no solution for both issues with git older than mentioned version/commit above!**

**Comment by r-stein** [comment] 2017-05-29 18:10
@deathaxe can't we just check the git version and select the corresponding diff method? Even if we create a setting `"diff_method": "traditional"/"archive"/"cat-file"` (with comment documentation), it would be okayish. However IMO it should have precedence to support all git versions, which ship with the common package managers, over supporting all project setups.

**Comment by deathaxe** [comment] 2017-05-29 19:50
Added a commit with a fallback to `git cat-file -p` on legacy git versions. Can someone with such an old git check this please?

**Comment by deathaxe** [comment] 2017-05-29 19:52
> @r-stein is right. version 2.11 isn't available yet for Fedora 25 through the official repos and I guess that's the same on other distros.

And this is why everybody blames Linux the better OS with better update support than Windows?

**Comment by tedmiston** [comment] 2017-05-29 19:54
Following the suggestions of @pixilation, here's a fix for OS X / macOS:

First, I ran the GitGutter support command (`Preferences > Package Settings > GitGutter > Support Info`) which yielded some confusing comments (it is installed via PC).

<img width="532" alt="screen shot 2017-05-29 at 3 33 12 pm" src="https://cloud.githubusercontent.com/assets/366688/26560707/b8a6351c-4486-11e7-964d-8d5abc072891.png">

Anyway, I upgraded git to the latest version in Homebrew:

	$ brew upgrade git
	...
	==> Summary
	🍺  /usr/local/Cellar/git/2.13.0: 1,463 files, 33.4MB

	$ git --version
	git version 2.13.0
	hub version 2.2.9

After restarting Sublime and disabling / enabling the GitGutter package the issue persisted.  I removed the package which led to the rare occurrence of sending Sublime into a spinning beachball then required force quit.  I repeated this process and still saw the fully green GitGutter. 
 Removing it a second time reproduced crashing Sublime again.

Finally, I followed @agungyuliaji's suggestion to point `git_binary` to the Homebrew version which solved it.  While in settings, I also dropped `debounce_delay` from 1000 (default) to 0 which made the diff icons appear noticeably faster.

**Comment by deathaxe** [comment] 2017-05-29 20:05
@tedmiston : 

1. You might need to install https://github.com/int3h/SublimeFixMacPath on MacOSX to let GitGutter find git. Sublime Text is known to use different environment variables or even completely different environment than your login shell. 

2. The `debounce_delay` is normally used during typing. Each change after a 200ms period should be evaluated already. If you type quick without break GitGutter will wait until you're done. **Caution:** Each time GitGutter starts an evaluation, the whole content of the view is written to disk, which might become much, with `debounce: 0`. I wouldn't recommend to use values smaller than 500.

3. I found and fixed the reason for Git and GitGutter version not being displayed in the "Support Info" dialog some mins ago.

**Comment by clefebvre** [comment] 2017-05-29 20:11
@deathaxe testing git master with git 2.7.4 here (Mint 18.x) and gitgutter is working fine :)

**Comment by tedmiston** [comment] 2017-05-29 20:16
@deathaxe Thank you!  I just installed the Fix Mac Path package, removed overriding the binary setting, and amended my above comment.  I'll check the support info dialog again once the Sublime package update is released.

**Comment by r-stein** [comment] 2017-05-29 20:59
@deathaxe @jisaacks Since the change seem to work we should cut 2.7.1 soon to fix this issue for everyone.

**Comment by deathaxe** [comment] 2017-05-29 21:07
Done!

**Closed** 2017-05-30 14:52 UTC

**Comment by tedmiston** [comment] 2017-05-30 17:15
@deathaxe Just to circle back, the Support Info dialog is now working as expected in the new version.

**Comment by deathaxe** [comment] 2017-05-30 20:26
Thanks
