### ISSUE TITLE
All lines of all existing files shows as newly inserted

### ISSUE THREAD

**Issue by berginpanimayam** [jisaacks/GitGutter#388] opened 2017-03-14 14:23 UTC
After installing mac OS Sierra, all lines of all files are showing as new inserted (+).
When I change the file and save, I can see the actual changed line in sourcetree, but sublime shows the lines as inserted even after modifying the line.
![screen shot 2017-03-14 at 10 20 28 am](https://cloud.githubusercontent.com/assets/6225164/23905022/2ddcb40a-08a0-11e7-9e32-d42c5fe9f9e2.png)

**Comment by deathaxe** [comment] 2017-03-14 16:33
1. What about the status bar message? What does it show?
2. Any output in the console?

This issue is most likely be caused by a failed git call, which looks like the file in repository was empty.

You could check the following:

1. cd to your repository's root:
2. Call `git rev-parse HEAD`
3. Copy the returned commit hash (e.g.: 0f02d04a)
4. Call `git archive --format=zip <hash> <filename> > test.zip`
5. Try to open the test.zip and check whether it contains the file and correct content.

Note:
- `<hash>`: is the output from 3.
- `<filename>`: is the relative path to a file within your working tree.

This is basically what GitGutter does in order to read a file from repository.

**Comment by lestrato** [comment] 2017-03-14 17:55
Hi there,

I'm also getting the same issue, and this happens to all of my files in the project.
I checked what you recommended and found that the files are, in fact, identical. To be sure, I did a git pull affirming that I am up to date with my remote.

In console, I get the following errors:
> Unable to open /home/useme/.config/sublime-text-3/Packages/GitGutter/GitGutter.sublime-settings
> Unable to open /home/useme/.config/sublime-text-3/Packages/User/GitGutter.sublime-settings
> Unable to open /home/useme/.config/sublime-text-3/Packages/User/gitgutter_popup.css
> Unable to open /home/useme/.config/sublime-text-3/Packages/GitGutter/gitgutter_popup.css
> Unable to open /home/useme/.config/sublime-text-3/Packages/GitGutter/GitGutter.sublime-settings
> Unable to open /home/useme/.config/sublime-text-3/Packages/User/GitGutter.sublime-settings
> Unable to open /home/useme/.config/sublime-text-3/Packages/GitGutter/Default (Linux).sublime-keymap
> Unable to open /home/useme/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap

Perhaps something fail during installation?

**Comment by deathaxe** [comment] 2017-03-14 18:14
When do you get those output? On loading ST3 or when opening on of those files? Do those output apply to GitGutter related files only? Do the "Preferences: GitGutter Settings" commands open the files?

Did you install GitGutter using Package Control or did you pull from git directly? Make sure to have only one GitGutter installed. It must exist only in `/home/useme/.config/sublime-text-3/Packages/GitGutter` if pulled from git or in `/home/useme/.config/sublime-text-3/Installed Packages/GitGutter.sublime-package` if installed using Package Control.

I never saw those errors. Looks as they are locked by another process or so.

**Comment by m45yang** [comment] 2017-03-14 21:10
+1 on this issue, seeing the same problem right after upgrading to macOS Sierra.

**Comment by bboru21** [comment] 2017-03-15 14:33
This issue was resolved for me here:

**Comment by lestrato** [comment] 2017-03-15 14:43
A reinstall fixed the issue for me.

**Comment by deathaxe** [comment] 2017-03-15 17:20
#381 is about lines being displayed as modified due to different line endings. This issue here is caused by something else. A file access error or something like that.

**Comment by kuba-wyrostek** [comment] 2017-03-15 19:14
Seems it have nothing to do with macOS Sierra. I am still on 10.11 and since recently all lines in all my versioned files are marked with yellow rectangle. Disabling/enabling did not help. Neither reinstalling. I see no messages in console.
![screen shot 2017-03-15 at 20 11 28](https://cloud.githubusercontent.com/assets/4232947/23966515/eca7ef3c-09bb-11e7-8480-28f4d8977d0f.png)

**Comment by berginpanimayam** [comment] 2017-03-16 05:12
I even tried reinstalling git and gitgutter but still have the issue.

**Comment by deathaxe** [comment] 2017-03-16 16:26
@berginpanimayam: please answer the questions of post 2. Without any information issue can't be resolved. It's working fine for Windows and Linux on ST2 and 3 for me. So I need some info to get an idea, what could be wrong.

**Comment by m45yang** [comment] 2017-03-20 17:53
@deathaxe 
Output in console when installing GitGutter:

```
ignored packages updated to: ["GitGutter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_gutter_jump_to_changes
reloading plugin GitGutter.git_gutter_popup
reloading plugin GitGutter.git_gutter_settings
reloading plugin GitGutter.git_gutter_show_diff
reloading settings Packages/GitGutter/GitGutter.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

Also, I repeated the steps given in post 2 and the zip file does in fact contain the correct content.

**Comment by deathaxe** [comment] 2017-03-20 18:56
The console output of the installation looks good so far. Everything fine. If `git archive` returns a valid zip file with correct content when executed from normal terminal, we need to check further things.

**What does the status bar show if you work on a file which is part of a git repository?**

You should see something like:

`In Repository on Branch, File is modified, 4+ 3-, ...`

**Are all information there as expected?


The latest GitGutter release `1.5.1` prints error messages from git to console. Do you see messages in your console that look like:

`GitGutter 'git archive' failed with "fatal: ...."`

If you don't see any message like that and no traceback to an unhandled exception can be found in console, the issue might be caused by file decoding.

GitGutter tries to decode the file read from git using the current view's encoding with a fallback to utf-8. If this fails, an empty temporary git file is written to disk, which would then result in all files being marked as inserted.

What file encoding do you use?

Do you have `Convert​To​UTF8` plugin installed and in use?

**Comment by m45yang** [comment] 2017-03-20 20:57
@deathaxe 
There seems to be a problem with what's shown on the status bar. It's showing:
`In <repo_name> on **b"**, File is inserted, Line <line_number>, Column <column_number>`
It's displaying `b"` instead of the actual branch name.

Git archive doesn't print any failure messages, and I'm using UTF-8 file encoding.

Another message that just popped up on the console is this, hopefully it might be of some help:
`indexing [job 986]: no files were indexed out of the 2 queued, abandoning crawl`.

Thanks so much for your help!

**Comment by deathaxe** [comment] 2017-03-21 17:41
It looks like the output read from git is always empty, which is in fact a very strange thing especially with the call of `git rev-parse --abbrev-ref HEAD`, which is used to read the current's branch name. If no error message is displayed and/or no exception it might be an issue related it is quite hard to guess the reason. 

1. Do you use other plugins which use git or external programs? 
2. Do they work normally? 
3. Do we talk about ST2 or ST3?
4. Maybe you've got the chance to check both versions?

It looks like an issue related to process spawning or inter-process communication. GitGutter as well as other plugins follows the recommendations from python docs for running external programs. But something seems wrong with it at all.

GitSavvy as an example uses the same function calls to run git. Does it work?

Can you try with the following setting in _GitGutter.sublime-settings_ ?

`"git_binary": "git",`

This forces GitGutter to run git command without any path specifications, just as you do when calling git from shell.

**Comment by henhan** [comment] 2017-03-21 18:29
I had exactly this issue, and just managed to solve it! Thanks for your suggestion to test other git plugins, that got me on the right path.

Turned out that Sublime was using the git installation that is provided by Xcode, while I am using git from homebrew in my shell. Xcode was updated a few days ago, and I had not yet agreed the terms, which caused all git commands that sublime tried to run to show "Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo."

I found two solutions, both solve the problem:
1. Just agree the Xcode terms if you want to use that (older) version of git. (run `sudo xcodebuild -license accept` in terminal)
2. Install the package "Fix mac path" to get Sublime to load the correct path that your shell will use, to get all Git plugins to use the same version that you do in your shell. (This obviously only goes for the case when you have two different git versions installed).

**Comment by m45yang** [comment] 2017-03-21 20:41
@henhan's solution fixed it for me, thanks!

**Comment by okjill** [comment] 2017-03-25 08:08
@henhan's solution worked like a charm. Thank you, this was driving me crazy!

**Comment by r-stein** [comment] 2017-03-25 10:23
It would be good, if someone adds a short solution in the [troubleshooting] section.

[troubleshooting]:https://github.com/jisaacks/GitGutter#-troubleshooting

**Comment by deathaxe** [comment] 2017-03-25 11:06
In fact we already have the solution in README already.

> On OSX you might need to install the package SublimeFixMacPath.

But you're right. This issue made me learn what's the sense of this package actually is.

**Comment by matneves** [comment] 2017-04-26 14:16
Temporary fix:
1 - Remove GitGutter
2 - Close Sublime
3 - Install GitGutter

**Comment by foxlance** [comment] 2017-05-02 12:09
I experienced the same issue. I'm using a fresh install of Windows 10 and Git 2.12.2. All lines have the `plus` symbol. Looking at the console, I get:
```
GitGutter: "git rev-parse" failed with "[WinError 2] The system cannot find the file specified"
GitGutter: "git ls-files" failed with "[WinError 2] The system cannot find the file specified"
GitGutter: "git ls-files" failed with "[WinError 2] The system cannot find the file specified"
GitGutter: "git rev-parse" failed with "[WinError 2] The system cannot find the file specified"
```
The `ignore_whitespace` advice wasn't working for me. What worked for me was:
```
// GitGutter Settings - User
{
   "git_binary": {
        "default": "",
        "windows": "C:/Program Files/Git/cmd/git.exe"
    },
}
```
This must be caused by a random option selected during install of git where I selected **Use git only from git-bash** (I think).

**Comment by deathaxe** [comment] 2017-05-02 16:03
The path to the git.exe must be part of the PATH environment variable. Means you must be able to just call `git` in the CMD.

**Comment by ColdwindZhao** [comment] 2017-05-12 16:36
i meet the same problem, solved by using

> GitGutter.sublime-settings  "git_binary": "git",

**Comment by deathaxe** [comment] 2017-05-12 18:36
> **GitGutter.sublime-settings "git_binary": "git",**

In this case you can leave this setting empty as it is the internal default value.

**Comment by tigertooth01** [comment] 2017-05-29 04:15
I am seeing this in Windows 10 machine. It was working fine on Friday, but when turned ON on Monday, this happens!? I am able to call "git" from CMD. It's working fine with SourceTree as well. How to debug this?

**Comment by zacurry** [comment] 2017-05-29 06:28
@tigertooth01  I am having the same problem.Everything was working fine on friday. Please let me know if you find the solution!

**Comment by zacurry** [comment] 2017-05-29 06:37
@deathaxe I followed your 5 steps, and was able to get the full correct file as output. Any ideas ? Multiple users seem to be having this issue . I am on a windows 10 and using sourcetree.

**Comment by asantamar** [comment] 2017-05-29 07:43
Same issue here as @tigertooth01 and @zacurry. Tried both with **"ignore_whitespace": "eol"** and **"git_binary": "git"** but the problem persists (all the files appear as if they were just inserted). I am running Ubuntu 16.04, and Sublime Text 3, build 3126 and I can run successfully "git" from the terminal. Any hints on this?

**Comment by tuanngominh** [comment] 2017-05-29 08:05
I have suddenly have this issue today. Already tried with
- Changing `git_binary` to `git` or to `/usr/bin/git` or remove that setting (My `which git` is `/usr/bin/git`)
- Install `SublimeFixMacPath` package
- run `sudo xcodebuild -license accept` in terminal

I am on `10.11.6 OSX El Capitan`

> git --version
git version 2.7.4 (Apple Git-66)

The only issue I can think of is I have just updated my node version from v4 to v6. I install new node by download osx installation package then install it.

Sublime3 status bar
![screenshot_5_29_17__3_02_pm](https://cloud.githubusercontent.com/assets/2210733/26541497/17252cd0-4480-11e7-8705-4252a64fb0fc.jpg)

**Comment by tigran-muradyan** [comment] 2017-05-29 08:18
+
same issue on linux mint 18.1,
it looks like the issue raised on after today automatic update of ST3 GitGutter plugin

any idea how I can solve the issue?

**Comment by procoder317** [comment] 2017-05-29 09:30
same issue in linux mint 18.1 for me also in sublime text today

**Comment by paleja** [comment] 2017-05-29 10:18
installation of Gitignore plugin solved my problem

**Comment by jlanzarotti** [comment] 2017-05-29 10:55
+1 on this... same issue on OSX 10.11.6 Sublime 3 3126

**Comment by TaoriYu** [comment] 2017-05-29 11:01
same problem on ubuntu 14.04, ST3 build 3126
test.zip archive contains absolutely valid version of file, and there is no any error message at the st console while reinstalling GitGutter.

**Comment by protopropanol** [comment] 2017-05-29 12:29
Same on ubuntu 16.04, ST3 build 3126
test.zip is OK, no console errors before or after reinstalling GitGutter.

**Comment by IvanAlegre** [comment] 2017-05-29 12:33
From #416 @glennr pointed out that installing 1.6.0 fixes the problem, to do:

```
rm ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/GitGutter.sublime-package
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/
git clone --branch 1.6.0 git://github.com/jisaacks/GitGutter.git
```

And in GitGutter options `"git_binary": "/usr/local/bin/git"`

Additionally I had to add GitGutter to ignored_packages, restart ST and then remove from ignored_packages (this is in User preferences in SublimeText)

**Comment by arsenicum** [comment] 2017-05-29 13:32
This is my output for **GitGutter: Support Info**:

```
- Sublime Text 3126
- Platform: linux
- Arch: x64
- GitGutter GitGutter version could not be acquired!
- Install via PC: False
- git version could not be acquired!
- mdpopups 1.13.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8
```

Seems like there is an error trying to find git and GitGutter. The checks for git and GitGutter are located  in the file `module/support.py`. I think the problem is a wrong `cwd` parameter for `subprocess.Popen` - look at lines [14](https://github.com/jisaacks/GitGutter/blob/1.7.0/modules/support.py#L14) and [29](https://github.com/jisaacks/GitGutter/blob/1.7.0/modules/support.py#L29). Error logged to the console:
```
GitGutter.sublime-package: [Errno 2] No such file or directory: '/home/arsenicum/.config/sublime-text-3/Packages/GitGutter.sublime-package'
```

But package installed with **Package Control** will have `~/.config/sublime-text-3/Installed Packages/` path.

**Comment by ozanhazer** [comment] 2017-05-29 15:09
My console reports:

```
GitGutter.sublime-package: resource not found
GitGutter.sublime-package: [Errno 2] No such file or directory: '/Users/ozanhazer/Library/Application Support/Sublime Text 3/Packages/GitGutter.sublime-package'
```

**Comment by AiryShift** [comment] 2017-05-29 15:45
@IvanAlegre In addition, #416 mentions upgrading git to v2.11 (and above) seems to have worked. I can confirm this to work on Fedora 25.

**Comment by fuumashirou** [comment] 2017-05-29 15:50
What @arsenicum  said is the same thing that is happening to me. But I don't know how to solve it.

**Comment by carlosfrodriguez** [comment] 2017-05-29 17:11
Same on me

GitGutter.sublime-package: resource not found
GitGutter.sublime-package: [Errno 2] No such file or directory: ...

**Comment by ftuyama** [comment] 2017-05-29 17:57
Same here

**Comment by Fauzyy** [comment] 2017-05-29 18:37
I also ran into this for OSX 10.11.6 and ST 3

Updating git from 2.4.3 -> 2.13.0 fixed the issue.

**Comment by deathaxe** [comment] 2017-05-29 19:56
This issue was caused by introducing `git cat-file --filters` to fix both (#74, #409). I wasn't aware of it to be supported by git 2.11.0+ only. Added a fix to fallback to `git cat-file -p` if older git is detected. This will reintroduce #74 for those people, but there is no other solution.

**Comment by carlosfrodriguez** [comment] 2017-05-29 23:22
Version 1.7.1 works for me, thank you @deathaxe.

**Comment by MohannadNaj** [comment] 2017-05-30 02:21
as @tigran-muradyan mentioned, had the same issue after the latest automatic update of GitGutter.

Windows 7- 64bit, ST3 Build 3126, Git 2.8.3.windows.1

Removing the package then re-install it, solved the issue for me.

**Comment by tigertooth01** [comment] 2017-05-30 03:39
@deathaxe Yes, 1.7.1 fixed the issue. I'm not concerned about #74 just yet!

**Comment by r-stein** [comment] 2017-05-30 05:59
If someone really run into #74 it is IMO acceptable to say "You need to update you git to version `2.11+`", but it should and does just work for the simple cases.

**Comment by coolynx** [comment] 2017-07-09 14:41
I have the same issue but with remark - it works partly. So, it may be a hint why it does not work for others. 😄 

Just updated and tested everything (or almost) I found on this thread and still have the same issue.

> - Sublime Text 3126
> - Platform: osx
> - Arch: x64
> - GitGutter 1.7.2
> - Install via PC: True
> - git version 2.13.2
> - mdpopups 2.1.1
> - markdown 2.6.6
> - pygments 2.1a0
> - jinja2 2.8

Here is the hint.

GitGutter works as expected on repositories where `.git` is inside the working tree and in cases where `.git/` directory is outside the working tree it does not work.

So, is it possible to define `worktree` somewhere for gitgutter or give it a hint?

**Comment by deathaxe** [comment] 2017-07-10 17:16
There is no setting to do so. If you want to work with multiple/custom work-trees per repository you need to use `git worktree add` to checkout a custom work-tree from your repository. This creates a `.git` file which is resolved by git just like submodules are.

**Comment by coolynx** [comment] 2017-07-10 17:35
@deathaxe, I was not clear enough. Here is the way to reproduce the bug.

```
cd /home/user/whatever/tmp
git init
# creates .git/ directory inside tmp
git add .
git commit -m "initial commit"
subl .
```
And we have a nicely working Sublime Text with GitGutter.

```
# move .git directory away
mv .git ../
vim .git/config
# add path
worktree = /home/user/whatever/tmp
subl .
```
And now we have a not working plugin were all files are newly added.

**Comment by deathaxe** [comment] 2017-07-10 20:42
GitGutter uses python builtin `path` module to check whether you are within a worktree. Therefore it expects either a `.git` file or directory in the root of a worktree - the standard for ages. Otherwise git would need to be called for each view no matter whether we are within a repo or not. And even with being within a repo this would add just another 100ms of delay on Windows as this is the minimum required time to execute an external command.

**Comment by alariva** [comment] 2017-07-11 19:31
A GitGutter reinstall fixed issue for me.

```
SublimeText 3126
16.04.1-Ubuntu SMP
git version 2.7.4
```

**Comment by jnovack** [comment] 2017-07-17 20:58
This occurred after I installed `bash_completion` on my Mac (from source), and modified my `.bashrc`.  I'm not sure if it's related, just adding a data point.

`rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/GitGutter/` and reinstalling via **Package Control** fixed it.

**Comment by deathaxe** [comment] 2017-08-02 17:41
> rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/GitGutter/ and reinstalling via Package Control fixed it.

Seems you were using the master branch directly. It should not but may contain some issues not cached by testing for some edge cases. Qualified feedback about latest commits is always welcome to help finding and fixing remaining issues before making a release.

**Comment by redbar0n** [comment] 2017-08-24 12:32
Having the same problem here, and I'm on OSX 10.9.5 Mavericks. It quite recently appeared, maybe a few weeks ago, maybe after an update. Here are my system stats, in case it might help debugging:

- Sublime Text 3126
- Platform: osx
- Arch: x64
- GitGutter 1.7.4
- Install via PC: True
- git version 1.7.4.4
- mdpopups 2.1.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

A reinstall didn't fix it for me.

A curious thing is that the aforementioned 'GitGutter: Support Info' says:
`git version 1.7.4.4`

But running this in terminal gives:
```
› git --version
git version 2.4.5
```

**Comment by redbar0n** [comment] 2017-08-24 12:55
Upgrading git solved the problem for me!

"GitGutter: Support Info" now says:
`- git version 2.14.1`

And terminal says:
```
› git --version
git version 2.14.1
```

**Comment by deathaxe** [comment] 2017-08-24 18:07
> But running this in terminal gives: ...

ST doesn't run in user shell environment by default and therefore may use other versions of shell programs as found on the PATH.

**Comment by deathaxe** [comment] 2017-09-18 16:57
All of the issues discussed in this thread were either resolved
- end of line mangling bug
- git cat-file --format not supported by git 2.10 and before (1f05f50)

The other major issue of git not being found by Sublime Text can be resolved by https://github.com/int3h/SublimeFixMacPath which was added to the troubleshooting section.

In order not to create too much confusion about already resolved issues I close the quite big thread at this point.

**Closed by deathaxe** 2017-09-18 16:57 UTC
Labels: OSX, question
