### ISSUE TITLE
GitGutter makes Sublime unresponsive

### ISSUE THREAD

**Issue by borislavgrigorov** [jisaacks/GitGutter#493] opened 2018-04-11 00:02 UTC
## Description
GitGutter seems to be slowing down some Sublime Text 3 functions.

## Support Info
Sublime version: Sublime Text 3 Build 3143

## Steps to Reproduce Issue
Navigate between different files in source control.
This causes Sublime to stall and become unresponsive.

**Comment by deathaxe** [comment] 2018-04-12 18:07
The one and only function being executed synchronously is `git --version` which is responsible to check for git to work properly. This function normally returns its result in 5ms on Linux and in 50ms on Windows, which is short enough to not realize it.

All other functions are executed in dedicated threads and can't block ST.

I saw ST stalling caused by GitGutter only once maybe half a year ago. It was caused by Kaspersky Internet Security, which caused `git --version` to require up to 1.5 seconds to return a value. This issue was resolved after upgrading Windows 10 and KIS.

**Comment by borislavgrigorov** [comment] 2018-04-12 18:57
Hi,

I tried git --version and it takes 5 seconds for me. Perhaps that is the
issue. Why do you have this command be synchronous? It does stall ST.

Regards,
Bobby

**Comment by r-stein** [comment] 2018-04-12 19:16
We use this command to decide whether we should enable gitgutter at all as you can see [here](https://github.com/jisaacks/GitGutter/blob/master/modules/commands.py#L95). If it is a serious issue for you, you can use PackageResourceViewer and delete these two lines as workaround.

**Comment by deathaxe** [comment] 2018-05-01 19:40
As this issue is caused by a delayed reaction of `git` itself, I labeled this issue invalid and don't see a way how GitGutter could fix such kind of issue.

Even if ST wouldn't freeze, the user experience would be bad anyway due to heavy delays.

**Comment by borislavgrigorov** [comment] 2018-05-01 19:50
You can make the git --version command run asynchronously.

**Comment by rahul-ramadas** [comment] 2018-05-04 14:51
Is it possible to maybe provide a workaround that allows turning off the functionality to check for a valid git installation? If the workaround is active, the plugin could simply assume that git is installed. The workaround would of course default to being disabled, but users who are seeing delays can choose to activate the workaround, at their own risk.

This workaround simply mirrors your suggestion above to delete the lines (I tried it and it works fine; I also had to fixup some code that checks the git version to see if a particular git feature is present), except that building it into the plugin means that people don't have to redo it on every update.

**Comment by r-stein** [comment] 2018-05-04 16:08
I also think we could add a `"dont_validate_and_assume_git_version":  "1.7.2"`, which will disable the call and on validate and just directly uses that version number if the setting is present and not empty.

**Comment by deathaxe** [comment] 2018-05-04 16:29
It's not only the version string which is interesting, but the information, whether git is still on duty. If it was only the version, it could be read upon startup once and cached for lifetime.

In fact most (all) posted issues about "all lines are marked as new" were a result of git not working properly or returning nonsense, which is hard to catch with the current implementation of Promises as they don't support an `on_error` callback.

If we remove the version check I promise such issues to be posted in the near future again and again.

Based on `git --version` a clear status message is printed to console, if git stops working or returns back on duty. In the meanwhile all menu items are disabled and commands are hidden. 

On the other hand ask yourself the question about the quality of the user experience, if the changes you made to the text are added to the gutter with a delay of about 10 seconds? At least 2 git calls are required for evaluation. If `git --version` takes about 5secs already, how long will real calls do?

**Comment by r-stein** [comment] 2018-05-04 16:36
I would add that option as opt-in and for only those people who really have such a performance issue.

**Comment by deathaxe** [comment] 2018-05-04 18:29
Maybe #497 can reduce the number of freezes and improve the situation with only a few code changes.

**Comment by deathaxe** [comment] 2018-07-04 17:01
Any experiences about possible improvements on that with the latest GitGutter version?

**Comment by rahul-ramadas** [comment] 2018-07-05 15:10
Seems much better, I just occasionally notice a small hang on opening a file, which I guess is expected.

**Comment by deathaxe** [comment] 2018-07-05 16:08
The version needs to be checked at least once after opening a file as it is theoretically possible to have per file config for different git applications.

**Closed by deathaxe** 2018-07-05 16:08 UTC
Labels: invalid, wontfix

**Comment by atstockland** [comment] 2021-01-08 18:04
This seems to be still relevant in v 1.11.3.  I had to remove GitGutter due to how laggy it made ST3.
