### ISSUE TITLE
GitGutter isn't working on OSX Sublime Text 3

### ISSUE THREAD

**Issue by gespinha** [jisaacks/GitGutter#152] opened 2014-03-14 00:01 UTC
Hi there,

I have installed and reinstalled various times GitGutter and it still doesn't work. I have tried verifying if I am using git and it is on. What should I do to diagnose my problem?

Thanks

**Comment by ahaarnos** [comment] 2015-02-09 17:52
I can offer a +1 for [SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) fixing my issue with GitGutter not working.

**Comment by daniisco** [comment] 2015-03-12 07:52
Can someone help me. I installed sublime text 3 yesterday and I have installer Gitgutter and the Fix path but it doesnt work. What do I do?

**Comment by Pictor13** [comment] 2015-03-20 16:37
I would add the I thought to have the same issue.
Then I checked better and I found a problem with PHPCS not correctly running.
After fixing PHPCS there were no other errors in the console, and GitGutter seemed to be correctly 
installed (as in this Issue).

After a little I realised that simply **PHPCS was hiding the GitGutter's icons** cause of some problems in the code.

I suggest you to press CMD+SHIFT+P and execute the "PHP Code Sniffer: Turn Execute On Save Off".
This way you should see correctly the icons!

If it _IS_ installed and you _DO NOT SEE_ any error, then everything is working ok. Just there is something else _"covering"_ the icons. So mainly check for other extensions that could provoke the problem!

**Comment by daniisco** [comment] 2015-03-20 17:17
Pictor13. When I press CMD+SHIFT+P do you want me to install the plugin PHPCs? What do you mean by execute the "PHP Code Sniffer: Turn Execute On Save Off". Sorry for the stupid question.

**Comment by Pictor13** [comment] 2015-03-25 15:16
daniisco, CMD+SHIFT+P (on _OSX_) is opening the "Command Palette"; the same you are getting going to the menu _"Tools -> Command Palette..."_.
That is one of the main features of Sublime, it allows you to execute whatever command you need and that is supported by Sublime.
Over there you have to write "PHP Code Sniffer: Turn Execute On Save Off", or even just the starting letters or part of the words (but in sequence).
You can type:
* _pcsteoff_
* _PHP Code Sniffer: Turn Execute On Save Off_
* _phpcs off_
they are equivalent.
Press ENTER.
Then you should get the extension PHPCS to not overriding (graphically) the GitGutter icons.

**Comment by daniisco** [comment] 2015-03-25 15:29
@Pictor13 It doesn't work to click enter, nothing happens :/

**Comment by Pictor13** [comment] 2015-03-25 17:19
When you press enter you just execute the command, that makes what it says: disables the sniffing of the code.
After that the other Sublime extension, _"PHP Code Sniffer"_, doesn't interfere with "GitGutter" and _should_ show the icons for the changes.

* Has the file you are testing been committed in a Git repository?
* Do you have on it any change in the code, respect to you last Gig commit?
* Do you have the PHP-CS (SublimeLinter-phpcs) extension?
** is it working?
** did you try to put some invalid code into the file, then save, to see if PHP-CS is raising any notice? (so that you are sure it is working)
** did you disable the PHP-CS behaviour with the command I was telling you? (_"Turn execute on save off"_)

My suggestion is relative to my case. There could be a possibility that in your case the problem is not a conflict with PHP-CS.

**Comment by plicjo** [comment] 2015-04-02 15:00
(SublimeFixMacPath)[https://github.com/int3h/SublimeFixMacPath] fixed this issue for me too.

**Comment by rajankur** [comment] 2015-04-07 18:39
This solved for me:

1. Added GitGutter in ignored_packages
2. Restarted Sublime Text
3. Removed GitGutter from ignored_packages

**Comment by jisaacks** [comment] 2015-06-18 02:28
Is this still an issue?

**Comment by trantorLiu** [comment] 2015-09-08 03:43
[SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) fixed this issue for me too.

**Comment by amerikan** [comment] 2015-09-17 20:39
My GitGutter had stopped working after I did a Mac update. The problem was being caused by Xcode, since it update I had to open and agree to its terms and conditions. After that GitGutter started working again.

**Comment by dansterrett** [comment] 2015-09-17 23:39
@amerikan's solution worked for me.

**Comment by giovannibonetti** [comment] 2015-09-18 23:06
Thanks, @amerikan! :+1:

**Comment by amerikan** [comment] 2015-09-19 01:05
@dansterrett @giovannibonetti Great! 

I found this out after running the `git` in my command-line. So if your GitGutter is not working first run `git` in your command-line first and go from there.

**Comment by bfcoder** [comment] 2015-09-22 15:02
:+1: Thanks @amerikan!

**Comment by emadalam** [comment] 2015-10-27 14:09
@amerikan :+1:

**Comment by eko3alpha** [comment] 2015-10-28 15:37
I just updated to El Capitan and found that GitGutter was no longer working on ST3, I manually ran

    git clone https://github.com/int3h/SublimeFixMacPath.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/FixMacPath

SublimeFixMacPath 
https://github.com/int3h/SublimeFixMacPath

**Comment by richkuo** [comment] 2015-10-30 18:13
@amerikan BRILLIANT! THANK YOU!!

**Comment by achilles-tee** [comment] 2015-11-11 07:59
@amerikan's solution alternative way
execute ```xcode-select --install``` in terminal will update the xcode as well.

**Comment by StewartDouglas** [comment] 2015-12-03 15:42
@amerikan :+1: thanks!

**Comment by cweekly** [comment] 2015-12-10 16:55
[SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) fixed this issue for me too.
I'm on st3, and simply installed it from package control.
It's a single python script that ensures your $PATH is available to Sublime, so it can find non-system binaries (eg homebrew packages).

**Comment by arhen** [comment] 2016-02-05 11:49
add this comment to sublime setting preference :

> "git_binary": "",
>   "compare_against": "HEAD",
>   "live_mode": true,
>   "focus_change_mode": true,
>   "non_blocking": true,

**Comment by eko3alpha** [comment] 2016-09-17 03:58
I just ran into another issue.  If you update Xcode and have not agreed to the license agreements GitGutter will stop working.

    You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.
    Hit the Enter key to view the license agreements at '/Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf'

Once I opened Xcode and agreed to the terms, GitGutter worked again.

**Comment by andrewchilds** [comment] 2016-10-25 20:06
GitGutter stopped working for me after I upgraded to El Capitan - installing the XCode command line tools with `xcode-select --install` got it working again.

**Comment by amerikan** [comment] 2016-10-25 20:15
@andrewchilds try this: https://github.com/jisaacks/GitGutter/issues/152#issuecomment-141605598

**Comment by rafaelcgo** [comment] 2016-11-17 20:14
Updated Xcode, `xcode-select --install`, restarted sublime.
Removed and Installed GitGutter.... Still won't work.

I'm running El Capitan

**Comment by rchl** [comment] 2016-11-17 22:09
> Removed and Installed GitGutter.... Still won't work.

Have you followed suggestion in the Readme to try SublimeFixMacPath?

**Comment by rafaelcgo** [comment] 2016-11-17 23:47
@rchl Tried both with no success. Is there a way to check if GitGutter is finding `git_binary`, maybe via sublime console?

I try the git gutter commands but no output is written on the console...

**Comment by rchl** [comment] 2016-11-18 08:44
@rafaelcgo If it couldn't find the binary then actually it should show a error dialog. So I guess that part might be working.

Try:
a) Restart sublime and open the console. Make sure that there no errors related to gitgutter (you can paste here if you want).
b) Make sure that git gutter package is not disabled (`Package Control: Disable Packages` should list it).
c) Make sure that you are trying it out on a file that is tracked by git.

**Comment by rafaelcgo** [comment] 2016-11-18 12:09
@rchl Thanks for the patience... Still not working. It used to work but I think the update crashed it somehow.

Steps 2 and 3 on video: https://youtu.be/HohNN2HCUYU


```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/rafaeloliveira/Library/Application Support/Sublime Text 3/Packages
state path: /Users/rafaeloliveira/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/rafaeloliveira/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.427512
first paint time: 0.509015
startup time: 0.510583
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin Fix Mac Path.FixPath
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_gutter_jump_to_changes
reloading plugin GitGutter.git_gutter_popup
reloading plugin GitGutter.git_gutter_settings
reloading plugin GitGutter.git_gutter_show_diff
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.promise
reloading plugin GitStatusBar.git_status_bar
reloading plugin Glue.__init__
reloading plugin Glue.Glue
reloading plugin Glue.GlueBrowser
reloading plugin Glue.GlueCmds
reloading plugin Glue.GlueIO
reloading plugin Glue.GlueSidebarOpener
reloading plugin LESS.less_completions
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin RSpec.OpenRSpecFile
reloading plugin RSpec.RSpecCreateModule
reloading plugin RSpec.RSpecDetectFileType
reloading plugin RSpec.shared
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-rubocop.linter
SublimeLinter: rubocop linter loaded 
reloading plugin SublimeLinter-ruby.linter
SublimeLinter: ruby linter loaded 
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Zen Tabs.TabsWorker
reloading plugin Zen Tabs.ZenTabs
reloading plugin Zen Tabs.ZenTabsTest
reloading plugin Guard.guard
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
Limit: 20
Full path: False
Highlight: True
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/05/p3_dh_4j6t11cp87vlc55zv00000gp/T/SublimeLinter3-rafaeloliveira 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/usr/local/bin
/usr/local/heroku/bin
/Users/rafaeloliveira/.rvm/gems/ruby-2.0.0-p481/bin
/Users/rafaeloliveira/.rvm/gems/ruby-2.0.0-p481@global/bin
/Users/rafaeloliveira/.rvm/rubies/ruby-2.0.0-p481/bin
/usr/local/heroku/bin
/Users/rafaeloliveira/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/bin
/usr/local/heroku/bin
/Users/rafaeloliveira/.rvm/gems/ruby-2.0.0-p481/bin
/Users/rafaeloliveira/.rvm/gems/ruby-2.0.0-p481@global/bin
/Users/rafaeloliveira/.rvm/rubies/ruby-2.0.0-p481/bin
/Users/rafaeloliveira/bin
/Users/rafaeloliveira/.rvm/bin
/Users/rafaeloliveira/.rvm/bin
 
SublimeLinter: ENV['GEM_HOME'] = '/Users/rafaeloliveira/.rvm/gems/ruby-2.0.0-p481' 
reloading settings Packages/User/Preferences.sublime-settings

```

**Comment by rchl** [comment] 2016-11-18 14:34
@rafaelcgo that looks quite tricky to figure out.
One last thing you should check is whether you get any error in the console on invoke one of '`Git Gutter: Compare Against...` commands. These commands don't catch exceptions like the main functionality, so it might show the problem.

If not, I don't think I have any more suggestions. Would probably need to debug by adding some debugging code...

**Comment by rafaelcgo** [comment] 2016-11-18 18:19
@rchl  No output. The only `GitGutter` command that has any output is `Show Comparing Against` which displays ' on a modal box "GitGutter is comparing against: HEAD"

:(

**Comment by rafaelcgo** [comment] 2016-11-22 18:57
@rchl It's working again. Don't have a clue what happened, but after a restart GitGutter has come back to life.

**Comment by deathaxe** [comment] 2017-09-16 15:11
I close this issue

- the original reason for this issue is quite old and out dated
- later parts of the discussion target [SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) as solution which is part of the trouble shooting section now.

**Closed by deathaxe** 2017-09-16 15:11 UTC
Labels: OSX, question

**Comment by amrutjadhav** [comment] 2017-09-22 07:20
@rajankur Adding it to ignore package, restart sublime and remove it from ignore package also works for me.
