### ISSUE TITLE
GG popups do not display: AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by taqtiqa-mark** [jisaacks/GitGutter#454] opened 2017-09-27 04:38 UTC
## Description
Git Gutter popups do not display.

## Support Info
- Sublime Text 3143
- Platform: windows
- Arch: x64
- GitGutter Version could not be acquired!
- Install via PC: True
- git version 2.14.1.windows.1
- mdpopups 2.1.1
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue
1. Delete ST3 `Data\Cache` folder
1. Start ST3
1. Open Console
1. Open git managed file with changes
1. Hover over GG git change symbol
1. Observe error msg in console

## Error
````
Traceback (most recent call last):
  File "C:\Users\<snip>\AppData\Roaming\SublimeText3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "modules.commands in C:\Users\<snip>\AppData\Roaming\SublimeText3\Data\Installed Packages\GitGutter.sublime-package", line 121, in run
  File "modules.popup.factory in C:\Users\<snip>\AppData\Roaming\SublimeText3\Data\Installed Packages\GitGutter.sublime-package", line 46, in show_diff_popup
  File "modules.popup.factory in C:\Users\<snip>\AppData\Roaming\SublimeText3\Data\Installed Packages\GitGutter.sublime-package", line 150, in _show_diff_popup_impl
  File "C:\Users\<snip>\AppData\Roaming\SUBLIM~1\Data\Packages\mdpopups\st3\mdpopups\__init__.py", line 499, in get_language_from_view
    keys = set(list(lang_map.keys()) + list(user_map.keys()))
AttributeError: 'NoneType' object has no attribute 'keys'
````

**Comment by deathaxe** [comment] 2017-09-27 10:12
This error is most likely caused by an invalid value of one of the language maps used by `mdpopups` to do highlighting.

Did you add/modify the `"mdpopups.sublime_user_lang_map"` in `%APPDATA%\Sublime Text 3\Packages\User\Preferences.sublime-settings`?

If it is set to `false` or `null`, the error you describe is triggered. 


It must be an object:

```
"mdpopups.sublime_user_lang_map": {
    // ...
}
```

This is not a GitGutter issue.

**Comment by taqtiqa-mark** [comment] 2017-10-03 01:24
Apologies for the delay.  I hadn't added/changed any mdpopups settings - I was pretty sure... until I browsed to `Preferences>Settings`: There I do see:

````
{
	"color_scheme": "Packages/Solarized Color Scheme/Solarized (light).tmTheme",
	"draw_white_space": "all",
	"ignored_packages":
	[
		"Vintage"
	],
	"mdpopups.sublime_user_lang_map": null,
	"mdpopups.use_sublime_highlighter": null,
	"rulers":
	[
		80
	],
	"tab_size": 2,
	"translate_tabs_to_spaces": true
}
````
What values should they be?
Apologies if I missed the instructions in readme, etc.

**Comment by r-stein** [comment] 2017-10-03 06:11
Just delete the two mdpopup settings.

**Comment by deathaxe** [comment] 2017-10-03 18:43
You can set `"mdpopups.use_sublime_highlighter": true` if you want to enable color highlighting. Otherwise none of them is required by default.

**Comment by deathaxe** [comment] 2017-10-05 15:56
I guess the question is answered and therefore close this issue.

**Closed by deathaxe** 2017-10-05 15:56 UTC
Labels: question

**Comment by taqtiqa-mark** [comment] 2017-10-08 20:25
Thanks.
