### ISSUE TITLE
Line annotations positioning in "Distraction free mode"

### ISSUE THREAD

**Issue by olls** [jisaacks/GitGutter#514] opened 2018-09-09 20:06 UTC
## Description

![screenshot_2018-09-09_20-59-12](https://user-images.githubusercontent.com/923336/45268413-c38f7e80-b473-11e8-8119-64aab0849c15.png)

The line annotation overlaps with the line text while I am in distraction free mode, as show in the image.

## Support Info

- Sublime Text 3176
- Platform: linux
- Arch: x64
- GitGutter b2a013a
- Install via PC: True
- git version 2.7.4
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

- Ensure line annotations are enabled in GitGutter settings.
- Go into distraction free mode ([shift]+[F11])
- Observe annotated lines overlapping with their annotations at the start of the line.

**Comment by deathaxe** [comment] 2018-09-10 16:35
The issue is caused by ST's core and can't be fixed by GitGutter. Therefore line annotations are disabled in distraction free mode for now.

**Closed** 2018-09-10 16:34 UTC
