### ISSUE TITLE
Turn Gitgutter off for untracked files (in addition to hiding icons)

### ISSUE THREAD

**Issue by DannyNemer** [jisaacks/GitGutter#204] opened 2014-12-10 21:25 UTC
I am working with several large JSON files, such that Gitgutter causes a lag when switching to a tab for one of the files (which is understandable given their size).

With `show_markers_on_untracked_file` set to `false` and `*.json` in `.gitignore`, Gitgutter correctly does not display icons for these files; yet, the lag persists.

Request: With this setting, is it possible for Gitgutter to not run at all for the ignored / untracked files, thereby removing the lag?

Thank you.

**Comment by Gabriel-p** [comment] 2015-06-16 02:23
Having the same issue. I work with large untracked `.dat` files and even with `"show_markers_on_untracked_file": false` the lag I get is so large it forces me to disable the plug-in every time I need to edit such a file.

**Comment by jisaacks** [comment] 2015-06-16 04:14
Does the lag go away if you set show markers on untracked files to true?

**Comment by Gabriel-p** [comment] 2015-06-16 11:16
No, it doesn't.

**Comment by jisaacks** [comment] 2015-06-16 15:45
@Gabriel-p so the thing is, when show markers on untracked files is `true` git gutter actually properly determines that the file is untracked and skips processing the diff. When it is set to `false` it does not make the check and still processes the diff, only a special rule that says if all the lines are marked as new (which they would be if untracked) it will not show any markers. This in and of itself is not great and should be fixed.

So if you have `"show_markers_on_untracked_file": true` and it is still lagging, then there is not much that can be done, because it is already not processing the file. It still needs to check if the file is tracked or not though. I do not think the size of the file would make a difference on the speed of which `git` can determine if the file is tracked or not. So I find it odd that you are still getting the error and it makes me think there may be some other issue going on.

**Comment by Gabriel-p** [comment] 2015-06-16 19:01
I just tried again.

I'm using sublime 3083, I disabled *all* packages installed except for `Package control` and `GitGutter`. This is what my user settings file looks like for this package:

````
{
  // Add a special marker on untracked files
  "show_markers_on_untracked_file": true
}
````

and this is the [data file I used for testing](https://gist.github.com/Gabriel-p/87575bf0dbfb49cd9e4c).

When the above file is located *outside* of any git repo, Sublime is as responsive as always if I edit it.

When I open that same file from *inside* a git repo where it is untracked and try to edit it, it's impossible. The `x` marks show in every line of the file indicating that the `"show_markers_on_untracked_file": true` feature is working.

Please let me know of anything I can do to help you debug this. I love this package and I don't want to have to remove it or be forced to disable it every time I need to edit a large un-tracked file.

Cheers.

**Comment by jisaacks** [comment] 2015-06-16 19:44
> or be forced to disable it every time I need to edit a large un-tracked file.

if you disable it does the problem go away?

Maybe just adding that many icons is causing sublime to lag. If so, the solution I proposed in Dec would fix that. It really should not be that difficult to implement if you want to give it a try. I could also answer any questions you have.

**Comment by Gabriel-p** [comment] 2015-06-16 23:53
Yes, if I disable the package  the issue goes away (shouldn't it? I mean, the issue is related to the package)

I'd love to help you out, I actually cloned the package yesterday and attempted a quick fix based on your Dec comment but the package is a bit more complicated than I expected and I have no experience debugging Sublime packages.

If I have some time I'll get on this in the following months. I'll let you know if I can come up with something.

Cheers.

**Comment by jisaacks** [comment] 2015-06-17 03:51
@Gabriel-p I went ahead and did the work myself. I also cut a pre-release `1.1.3` with this in it. Please install and let me know if that makes the situation better.

**Comment by Gabriel-p** [comment] 2015-06-17 12:33
The package updated to v1.1.3 and this issue is definitely gone. Thank you @jisaacks!

**Comment by jisaacks** [comment] 2015-06-17 13:18
Cheers!

**Closed by jisaacks** 2015-06-17 13:18 UTC
Labels: bug

**Comment by leo-thumbtack** [comment] 2017-07-25 22:52
I tried `show_markers_on_untracked_file` but didnt work for me.

**Comment by deathaxe** [comment] 2017-07-28 17:10
Your issue was caused by a Preferences.sublime-settings recently added to the package to support PackageDev's settings completion/linting/tooltips.

Unfortunately this file overrides all changes made to the GitGutter.sublime-settings.

I renamed it to Preferences.sublime-settings-hints which keeps PackageDev working and fixes your issue.

Alternatively all settings from GitGutter.sublime-settings can be placed into the Preferences by prefixing them with `git_gutter_`
