### ISSUE TITLE
GitGutter doesn't work

### ISSUE THREAD

**Issue by hiepnhl** [jisaacks/GitGutter#435] opened 2017-08-10 15:24 UTC
I just builded a new pc, installed GitGutter and... not working. Using Monokai Extended color scheme. No start up error:
>...
>reloading plugin Emmet.emmet-plugin
>reloading plugin GitGutter.plugin
>reloading plugin HTML5.encode_html_entities
>...

PATH is set:
>"git_binary": "C:\\\Program Files\\\Git\\\cmd\\\git.exe"

 GitGutter info:

![git](https://user-images.githubusercontent.com/5542627/29177629-5ddfa9d4-7e19-11e7-867e-36e1cf138d55.PNG)

Windows 10 ver 1703, Sublime 3 build 3126.

Could everyone tell me what wrong with my system? Thank you!!!

**Comment by deathaxe** [comment] 2017-08-10 16:37
Everything looks fine so far. I am using exactly the same configuration except I am on ST 3142 by default, but this shouldn't matter. The "git_binary" setting should not be required as GitGutter looks up git in the global PATH environment, which seems to be set correctly on your system.

Do you see any GitGutter message in the statusbar or does it keep completely quite? If yes, do you use _ConvertToUTF8_ package? It is known to mark the view as scratch while converting text but not resetting afterwards. GitGutter will keep disabled for scratch/readonly views.

Please see my first answer on #428 which contains a list of situations GitGutter is disabled.

**Comment by hiepnhl** [comment] 2017-08-10 20:40
I dont use ConvertToUTF8. Don't get any message from GG in the status bar, completely quite like you said (other packages works well, no problem with them). I even try a portable ver, install only package control, monokai extended, GitGutter, all setups are default and it still isn't working. 

And the funny thing is, I download Atom, install, test: The Git Diff doesnt work, even under `atom --safe`. WTH??? Getting cursed by an unidentified black magic?

So I guess the problem is not the Git Gutter and Sublime Text, it's someting else. I confuse so much, completely no clue! Git was installed in the default way.

**Comment by deathaxe** [comment] 2017-08-11 15:04
_Markdown Extended_ is a color scheme only. It doesn't cause the issue.

I guess the command pallet shows the "GitGutter: Support Info" and the "Preferences: GitGutter ..." commands only?

The file(s) you are editing are located in an ordinary working tree which was created using `git clone ...` or `git init` command? No submodule, no symlink/hardlinked file, etc.

Do you use english file names or some with unicode characters (e.g. Asian characters)? Maybe python has trouble with them even though it shouldn't?

GitGutter just calls a `cd <path_to_dir_of_open_file>` and `git ...` just as you would do from command line. Seems GitGutter or git don't recognize the file of being part of a valid repository maybe. 

You could ...
1. Open command pallet
2. Run "Preferences: GitGutter Settings"
3. add `"debug": true,`

This causes GitGutter to print out error messages received from git during evaluation. Maybe we get some helpful information this way. I don't see any obvious reason for your problems so far.

**Comment by deathaxe** [comment] 2017-08-25 14:44
Closing the issue because of missing feedback on an unconfirmed problem, which seems most likely not related to GitGutter.

**Closed by deathaxe** 2017-08-25 14:44 UTC
Labels: unconfirmed, waiting on feedback, Windows
