### ISSUE TITLE
GitGutter causes massive lag when editing over sshfs

### ISSUE THREAD

**Issue by egrefen** [jisaacks/GitGutter#230] opened 2015-05-17 11:05 UTC
I'm using ST3 with v1.1.2 of GitGutter to edit files on an sshfs mount on OS X 10.10.3.

GitGutter is causing massive lag (one or two seconds delay after a character is typed before it appears, spinning beach ball when switching tabs), in that normal behaviour resumes when GitGutter is disabled.

I tried setting `"non_blocking": true` in the GitGutter user config, but this did not help. I tried playing with various combinations of the other options, but to no avail. Only disabling GitGutter seems to work, when working remotely. Is there anything I should have tried that I haven't, or are other people encountering this too?

**Comment by jisaacks** [comment] 2015-05-26 15:48
This is a known issue. Git gutter is running git commands as you make changes to determine the icons to show. When you are editing a file over a network it will be having to run git commands over that network and will be very slow. The current answer is to not use git gutter when editing files over a network.

I would be open to ideas or PRs that attempt to solve this issue but it is not an issue I felt the need to try to solve since I think the majority use something like `vim` when editing files over a network.

Related: #79

**Comment by DecodedMonkey** [comment] 2015-05-27 15:39
I quick fix would be to add an option to turn off the constant checking and have it only check when a key cmd is pressed. This would allow for people to run the check once they have written some code.

**Comment by UltraNurd** [comment] 2015-08-18 16:52
I run into a similar issue when working on a file on a share mounted over SMB over VPN. (I cannot log directly into the storage appliance to run an editor, though I could get a shell on a closer machine.) It's definitely git that is slow (the commands can take a very long time when I run them in Terminal myself), but I'm not sure why it's locking up the Sublime Text UI when non_blocking is true.

**Comment by adityavm** [comment] 2015-11-14 21:34
:+1: This is still an issue. If `non_blocking: true` worked as intended, it would go a long way towards fixing this I feel.

**Comment by ddarbyson** [comment] 2016-06-10 02:15
Any updates on this issue? I'm mounting  SFTP drives via ExpanDrive 5 and having lag issues.

**Comment by rchl** [comment] 2016-11-07 16:33
Please re-open for now. That rewrite doesn't introduce async invocations yet. That will come next.

**Comment by jisaacks** [comment] 2016-11-07 16:44
Oops. That was an auto closing from the commit message I believe.

**Comment by rchl** [comment] 2016-11-08 20:21
More advanced users should feel free to test the fix for this in #321.

**Comment by rchl** [comment] 2016-11-12 10:31
#321 integrated. Should be resolved in versions newer than 1.3.0.

**Closed by rchl** 2016-11-12 10:31 UTC
